package com.nhathanh.until;

public class NewUntilities {

	public String bodyInviteTaskAcceptOrRefuse(String titleMail, String fullname, String projectName, String creator,
			String createDate, String content) {
		String body = "" + "\r\n" + "    <td align=\"center\" valign=\"top\">\r\n"
				+ "        <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" width=\"600\" class=\"m_-3947633973872345608container\" style=\"margin:0 auto\">\r\n"
				+ "            <tbody>\r\n" + "                <tr>\r\n"
				+ "                    <td valign=\"top\" bgcolor=\"#FFFFFF\">\r\n"
				+ "                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" role=\"presentation\" style=\"min-width:100%\" class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                            <tbody>\r\n" + "                                <tr>\r\n"
				+ "                                    <td class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                                        <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" role=\"presentation\">\r\n"
				+ "                                            <tbody>\r\n"
				+ "                                                <tr>\r\n"
				+ "                                                    <td align=\"center\">\r\n"
				+ "                                                        <a href=\"#\" title=\"\" target=\"_blank\" data-saferedirecturl=\"https://assets-global.website-files.com/62196607bf1b46c300301846/627120768c6e8b7f8e368a2a_hugo-illustration-calendar-extension.png\"><img src=\"https://f5-zpcloud.zdn.vn/168891876182483772/27f38fc9ece634b86df7.jpg\" alt=\"\" width=\"1200\" style=\"display:block;padding:0px;text-align:center;height:auto;width:100%\" class=\"CToWUd\" data-bit=\"iit\"></a>\r\n"
				+ "                                                    </td>\r\n"
				+ "                                                </tr>\r\n"
				+ "                                            </tbody>\r\n"
				+ "                                        </table>\r\n"
				+ "                                    </td>\r\n" + "                                </tr>\r\n"
				+ "                            </tbody>\r\n" + "                        </table>\r\n"
				+ "                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" role=\"presentation\" style=\"background-color:transparent;min-width:100%\" class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                            <tbody>\r\n" + "                                <tr>\r\n"
				+ "                                    <td style=\"padding:10px 0px\" class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                                        <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
				+ "                                            <thead>\r\n"
				+ "                                                <tr>\r\n"
				+ "                                                    <h1 style=\"text-align: center;\">" + titleMail
				+ "</h1>\r\n" + "                                                </tr>\r\n"
				+ "                                            </thead>\r\n"
				+ "                                            <tbody>\r\n"
				+ "                                                <h3 style=\"color: #4d536e;\">Hi, " + fullname
				+ "</h3>\r\n"
				+ "                                                <h3 style=\"color: #4d536e;\">From project: <b style=\"color: gray;\">"
				+ projectName + "</b></h3>\r\n"
				+ "                                                <h3 style=\"color: #4d536e;\">Creator: " + creator
				+ "</h3>\r\n"
				+ "                                                <h3 style=\"color:#4d536e\">Project creation date: <b style=\"color: red;\">"
				+ createDate + "</b></h3>\r\n"
				+ "                                                <p style=\"color: #4d536e;\"><b>Content:</b>"
				+ content + "\r\n"
				+ "                                                    reprehenderit corrupti autem aliquam, pariatur sapiente! </p>\r\n"
				+ "                                                <p style=\"color:#4d536e;text-align: center;\">Have you a nice day!</p>\r\n"
				+ "                                            </tbody>\r\n"
				+ "                                        </table>\r\n"
				+ "                                    </td>\r\n" + "                                </tr>\r\n"
				+ "                            </tbody>\r\n" + "                        </table>\r\n"
				+ "                    </td>\r\n" + "                </tr>\r\n" + "            </tbody>\r\n"
				+ "        </table>\r\n" + "    </td>\r\n" + "    </tr>\r\n" + "    <tr>\r\n"
				+ "        <td valign=\"top\">\r\n"
				+ "            <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" role=\"presentation\" style=\"background-color:transparent;min-width:100%\" class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                <tbody>\r\n" + "                    <tr>\r\n"
				+ "                        <td style=\"padding:0px\" class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                            <table style=\"width:100%\" role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
				+ "                                <tbody>\r\n" + "                                    <tr>\r\n"
				+ "                                        <td>\r\n"
				+ "                                            <table style=\"width:100%\" role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
				+ "                                                <tbody>\r\n"
				+ "                                                    <tr>\r\n"
				+ "                                                        <td style=\"width:100%;padding-bottom:0px\" class=\"m_-3947633973872345608responsive-td\" valign=\"top\">\r\n"
				+ "                                                            <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" role=\"presentation\" style=\"min-width:100%\" class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                                                                <tbody>\r\n"
				+ "                                                                    <tr>\r\n"
				+ "                                                                        <td class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                                                                            <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
				+ "                                                                                <tbody>\r\n"
				+ "                                                                                    <tr>\r\n"
				+ "                                                                                        <td align=\"center\" valign=\"top\">\r\n"
				+ "                                                                                            <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"m_-3947633973872345608MobileTableWidth\" width=\"87%\">\r\n"
				+ "\r\n"
				+ "                                                                                                <tbody>\r\n"
				+ "\r\n"
				+ "                                                                                                    <tr>\r\n"
				+ "                                                                                                        <td style=\"font-weight:400;line-height:20px;font-size:14px;text-align:center;color:#4d536e\" valign=\"top\">\r\n"
				+ "                                                                                                            *This offer is active until 9/22/2022 and cannot be combined with other offers, discounts, or applied to prior purchases. <a href=\"https://click.send.grammarly.com/?qs=75b1430b8b349ea32b26c08b7fae0049c189564d9406f1a6cdc52fc58cd0a739d689f47fc2d36f99d6d557eb71c280df4ebdb6cff0252bb212f7d756f4ad0e46\"\r\n"
				+ "                                                                                                                style=\"text-decoration:none\" title=\"Additional terms\" target=\"_blank\" data-saferedirecturl=\"https://www.google.com/url?q=https://click.send.grammarly.com/?qs%3D75b1430b8b349ea32b26c08b7fae0049c189564d9406f1a6cdc52fc58cd0a739d689f47fc2d36f99d6d557eb71c280df4ebdb6cff0252bb212f7d756f4ad0e46&amp;source=gmail&amp;ust=1666882994849000&amp;usg=AOvVaw1Z8--l7NVr_Y0COmwDLiSv\">Additional terms</a>\r\n"
				+ "                                                                                                            <a href=\"https://click.send.grammarly.com/?qs=75b1430b8b349ea3728110c24108e8d108474e5f6bfa746b2163beb9fe00d2b880ade01e11fbf175a9a1cb094611636a6372d9a1729f434ad1ac8fce9509dbd0\" style=\"text-decoration:none\" title=\"Additional terms apply\" target=\"_blank\"\r\n"
				+ "                                                                                                                data-saferedirecturl=\"https://www.google.com/url?q=https://click.send.grammarly.com/?qs%3D75b1430b8b349ea3728110c24108e8d108474e5f6bfa746b2163beb9fe00d2b880ade01e11fbf175a9a1cb094611636a6372d9a1729f434ad1ac8fce9509dbd0&amp;source=gmail&amp;ust=1666882994849000&amp;usg=AOvVaw2aoeSg6c82LlbR5LUxgQBY\">\r\n"
				+ "                                                                                                            </a>apply.<br>\r\n"
				+ "                                                                                                            <br> You received this offer for Grammarly Premium because you are currently opted in to receive them via your preference settings. You may adjust\r\n"
				+ "                                                                                                            your preferences at any time by clicking the link above.<br>\r\n"
				+ "                                                                                                            <br> This offer is not valid for Grammarly Business purchases.<br>\r\n"
				+ "                                                                                                            <br> © 2022 Grammarly, Inc. 548 Market St. #35410, San Francisco, CA 94104</td>\r\n"
				+ "                                                                                                    </tr>\r\n"
				+ "                                                                                                </tbody>\r\n"
				+ "                                                                                            </table>\r\n"
				+ "                                                                                        </td>\r\n"
				+ "                                                                                    </tr>\r\n"
				+ "                                                                                </tbody>\r\n"
				+ "                                                                            </table> <img border=\"0\" height=\"1\" src=\"https://assets-global.website-files.com/62196607bf1b46c300301846/627120768c6e8b7f8e368a2a_hugo-illustration-calendar-extension.png\" style=\"display:none\"\r\n"
				+ "                                                                                width=\"1\" class=\"CToWUd\" data-bit=\"iit\" jslog=\"138226; u014N:xr6bB; 53:W2ZhbHNlLDJd\"></td>\r\n"
				+ "                                                                    </tr>\r\n"
				+ "                                                                </tbody>\r\n"
				+ "                                                            </table>\r\n"
				+ "                                                        </td>\r\n"
				+ "                                                    </tr>\r\n"
				+ "                                                </tbody>\r\n"
				+ "                                            </table>\r\n"
				+ "                                        </td>\r\n" + "                                    </tr>\r\n"
				+ "                                    <tr>\r\n" + "                                        <td>\r\n"
				+ "                                            <table style=\"width:100%\" role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
				+ "                                                <tbody>\r\n"
				+ "                                                    <tr>\r\n"
				+ "                                                        <td style=\"width:100%;padding-top:0px\" class=\"m_-3947633973872345608responsive-td\" valign=\"top\">\r\n"
				+ "                                                            <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" role=\"presentation\" style=\"min-width:100%\" class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                                                                <tbody>\r\n"
				+ "                                                                    <tr>\r\n"
				+ "                                                                        <td class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                                                                            <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\r\n"
				+ "                                                                                <tbody>\r\n"
				+ "                                                                                    <tr>\r\n"
				+ "                                                                                        <td style=\"line-height:64px;font-size:64px\" height=\"64\">\r\n"
				+ "                                                                                            &nbsp;</td>\r\n"
				+ "                                                                                    </tr>\r\n"
				+ "                                                                                </tbody>\r\n"
				+ "                                                                            </table>\r\n"
				+ "                                                                        </td>\r\n"
				+ "                                                                    </tr>\r\n"
				+ "                                                                </tbody>\r\n"
				+ "                                                            </table>\r\n"
				+ "                                                        </td>\r\n"
				+ "                                                    </tr>\r\n"
				+ "                                                </tbody>\r\n"
				+ "                                            </table>\r\n"
				+ "                                        </td>\r\n" + "                                    </tr>\r\n"
				+ "                                </tbody>\r\n" + "                            </table>\r\n"
				+ "                        </td>\r\n" + "                    </tr>\r\n" + "                </tbody>\r\n"
				+ "            </table>\r\n" + "        </td>\r\n" + "    </tr>\r\n" + "    </tbody>\r\n"
				+ "    </table>\r\n" + "    </td>";
		return body;
	}

	public String bodyProject(String fullname, String projectName, String creator, String content) {
		String body = "<div style=\"font-family:Segoe UI,Calibri;font-size:16px;text-align:left\">\r\n"
				+ "        <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"line-height:1.5;width:100%\">\r\n"
				+ "            <tbody>\r\n" + "                <tr>\r\n" + "                    <td>&nbsp;</td>\r\n"
				+ "                    <td>\r\n" + "                        <div style=\"padding:15px\">\r\n"
				+ "                            <h1 style=\"text-align:center;color: rgb(2, 93, 50);\"><strong>Invitation to join the project</strong></h1> &nbsp;\r\n"
				+ "                            <div>\r\n"
				+ "                                <div style=\"text-align:center\">\r\n"
				+ "                                    <a href=\"\" target=\"_blank\" data-saferedirecturl=\"https://www.google.com/url?q=https://www.projectplan365.com/bluerain/click?e%3DbmhhdnRwczE2NTAwQGZwdC5lZHUudm4%26s%3DUHJvamVjdCBSZXBvcnRz%26d%3DSERJIFByb2plY3QgUmVwb3J0cw%26l%3DaHR0cHM6Ly93d3cucHJvamVjdHBsYW4zNjUuY29tL2hvdy1kby1pL3JlcG9ydHMv&amp;source=gmail&amp;ust=1672031083334000&amp;usg=AOvVaw2jP3cnyX4ey0ruR9XqvAbB\"><img alt=\"Total Slack\" src=\"https://f8-zpcloud.zdn.vn/3572285052569026289/d22dac9ba7b47fea26a5.jpg\" style=\"max-width:100%;width:800px\" class=\"CToWUd\" data-bit=\"iit\"></a>\r\n"
				+ "                                </div>\r\n"
				+ "                                <div style=\"max-width:100%;width:100%;\">\r\n"
				+ "                                    <p style=\"text-align:center\"><strong>Our project management system sends you an invitation to join the project!</strong></p>\r\n"
				+ "                                    <p style=\"text-align:center\"><b>Hi</b>, " + fullname
				+ "</p>\r\n"
				+ "                                    <p style=\"text-align:center\"><b>From project:</b> "
				+ projectName + "</p>\r\n"
				+ "                                    <p style=\"text-align:center\"><b>Creator:</b> " + creator
				+ "</p>\r\n"
				+ "                                    <p style=\"text-align:center\"><b>Project create date:</b> ngayTao</p>\r\n"
				+ "                                    <p style=\"text-align:center\"><b>Content:</b>" + content
				+ " </p>\r\n" + "                                    <div>&nbsp; &nbsp;\r\n"
				+ "                                        <p style=\"text-align:center\">Confirm at our app! </p>\r\n"
				+ "                                        <div style=\"text-align:center\"><img alt=\"Project Plan 365\" src=\"https://f8-zpcloud.zdn.vn/7887752381072662485/cd169305b82a6074393b.jpg\" style=\"width:250px\" class=\"CToWUd\" data-bit=\"iit\"></div>\r\n"
				+ "                                        <div style=\"text-align:center\">\r\n"
				+ "                                            <a href=\"#\"><img alt=\"YouTube\" src=\"https://ci3.googleusercontent.com/proxy/bSQw01IiHhRPXLVENgB3HESgdIrAUQMI3VfzgV66zFLsGafavZ6UTkKwwfoncLkzXJHUnDK6Pb29G67FY2p6T417TsEynP6jgkKK_gONo9JQjAt5FanSQHyBd6ICVzFDXsoI=s0-d-e1-ft#https://www.projectplan365.com/wp-content/themes/mpv/images/icons/youtube_50.png\"\r\n"
				+ "                                                    style=\"margin-left:6px;margin-right:6px;width:48px\" class=\"CToWUd\" data-bit=\"iit\"></a>\r\n"
				+ "                                            <a href=\"#\"><img alt=\"Linkedin\" src=\"https://ci5.googleusercontent.com/proxy/mhOvPo35c4LGTggQ630gtZClE74d67g898V8_Z8NI_w1hcCXss-R-9Y_AIhddjs7VKG7ie-1RxlBGxM2rjTCaQM7Oz0xpLST237iiru0HR17bEkli5u1wp8iL2Cq9Z6FYMBSLw=s0-d-e1-ft#https://www.projectplan365.com/wp-content/themes/mpv/images/icons/linkedin_50.png\"\r\n"
				+ "                                                    style=\"margin-left:6px;margin-right:6px;width:48px\" class=\"CToWUd\" data-bit=\"iit\"></a>\r\n"
				+ "                                            <a href=\"#\"><img alt=\"Facebook\" src=\"https://ci3.googleusercontent.com/proxy/iA4ewo_JTyOV2RNp7Z475Ta7jeeANljknS24q1w9FIzBfzTaIbvitWRdszQeKEmsV-55-CUb4qk08JhWBf62pPXAVGBbUYf64QmbEM_eCQFBAXQH3ku0bYLJcxFG9Yvme1lOXg=s0-d-e1-ft#https://www.projectplan365.com/wp-content/themes/mpv/images/icons/facebook_50.png\"\r\n"
				+ "                                                    style=\"margin-left:6px;margin-right:6px;width:48px\" class=\"CToWUd\" data-bit=\"iit\"></a>\r\n"
				+ "                                            <a href=\"#\"><img alt=\"Instagram\" src=\"https://ci6.googleusercontent.com/proxy/wZK6iIaXW5yZ8vuSSKGijurAL_7wPfUQ8-yUL2PSFBnoRGaQR0tQ54QO9k4Y5JLP2ZrUx0r8Zn5t3pLvSd_Jjc7XlBoDlixiqNYK9gVw_hhDyZhvpJRlfkqOTTqx7kb5Tiy8LaY=s0-d-e1-ft#https://www.projectplan365.com/wp-content/themes/mpv/images/icons/instagram_50.png\"\r\n"
				+ "                                                    style=\"margin-left:6px;margin-right:6px;width:48px\" class=\"CToWUd\" data-bit=\"iit\"></a>\r\n"
				+ "                                        </div> &nbsp;\r\n"
				+ "                                        <div style=\"text-align:center\">We are happy to assist you anytime.<br> If you need any help, please contact our <a href=\"IFByb2plY3QgUmVwb3J0cw&amp;l=aHR0cHM6Ly93d3cucHJvamVjdHBsYW4zNjUuY29tL3N1cHBvcnQv\" rel=\"noopener\" target=\"_blank\" ikOuLbQ8M \">support center</a>.</div>\r\n"
				+ "                                    </div> &nbsp;\r\n" + "                            </div>\r\n"
				+ "                        </div>\r\n" + "                    </td>\r\n"
				+ "                    <td>&nbsp;</td>\r\n" + "                </tr>\r\n" + "            </tbody>\r\n"
				+ "        </table>\r\n" + "    </div>";
		return body;
	}

	public String bodySetStatusSubTask(String titleStatusSubTask, String fromMail, String nameProject, String taskName,
			String time, String content) {
		String body = "\r\n" + "    <div style=\"margin:0;padding:0\" bgcolor=\"#FFFFFF\">\r\n"
				+ "        <table width=\"100%\" height=\"100%\" style=\"min-width:348px\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" lang=\"en\">\r\n"
				+ "            <tbody>\r\n" + "                <tr height=\"32\" style=\"height:32px\">\r\n"
				+ "                    <td></td>\r\n" + "                </tr>\r\n"
				+ "                <tr align=\"center\">\r\n" + "                    <td>\r\n"
				+ "                        <div>\r\n" + "                            <div></div>\r\n"
				+ "                        </div>\r\n"
				+ "                        <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"padding-bottom:20px;max-width:516px;min-width:220px\">\r\n"
				+ "                            <tbody>\r\n" + "                                <tr>\r\n"
				+ "                                    <td width=\"8\" style=\"width:8px\"></td>\r\n"
				+ "                                    <td>\r\n"
				+ "                                        <div style=\"border-style:solid;border-width:thin;border-color:#dadce0;border-radius:8px;padding:40px 20px\" align=\"center\" class=\"m_-6341730908529643193mdv2rw\"><img src=\"https://f7-zpcloud.zdn.vn/4413739648967792034/7dc7a6a46d8bb5d5ec9a.jpg\" width=\"250\" height=\"70\" aria-hidden=\"true\" style=\"margin-bottom:16px\" alt=\"Google\" class=\"CToWUd\" data-bit=\"iit\">\r\n"
				+ "                                            <div style=\"font-family:'Google Sans',Roboto,RobotoDraft,Helvetica,Arial,sans-serif;border-bottom:thin solid #dadce0;color:rgba(0,0,0,0.87);line-height:32px;padding-bottom:24px;text-align:center;word-break:break-word\">\r\n"
				+ "                                                <div style=\"font-size:24px\">Title status subtask </div>\r\n"
				+ "                                                <table align=\"center\" style=\"margin-top:8px\">\r\n"
				+ "                                                    <tbody>\r\n"
				+ "                                                        <tr style=\"line-height:normal\">\r\n"
				+ "                                                            <td align=\"right\" style=\"padding-right:8px\"></td>\r\n"
				+ "                                                            <td><a style=\"font-family:'Google Sans',Roboto,RobotoDraft,Helvetica,Arial,sans-serif;color:rgba(0,0,0,0.87);font-size:14px;line-height:20px\"><span class=\"il\">"
				+ fromMail + "</span></a></td>\r\n"
				+ "                                                        </tr>\r\n"
				+ "                                                    </tbody>\r\n"
				+ "                                                </table>\r\n"
				+ "                                            </div>\r\n"
				+ "                                            <div style=\"padding-top:20px;font-size:14px;line-height:16px;color:#5f6368;letter-spacing:0.3px;text-align:left\"><b>From Project</b>: "
				+ nameProject + "<br></div>\r\n"
				+ "                                            <div style=\"padding-top:20px;font-size:14px;line-height:16px;color:#5f6368;letter-spacing:0.3px;text-align:left\">In Task: "
				+ taskName + "<br></div>\r\n"
				+ "                                            <div style=\"padding-top:20px;font-size:14px;line-height:16px;color:#5f6368;letter-spacing:0.3px;text-align:left\">Time: "
				+ time + "<br></div>\r\n"
				+ "                                            <div style=\"padding-top:20px;font-size:14px;line-height:16px;color:#5f6368;letter-spacing:0.3px;text-align:left\">Content: "
				+ content + "<br></div>\r\n"
				+ "                                            <div style=\"padding-top:20px;font-size:14px;line-height:16px;color:#5f6368;letter-spacing:0.3px;text-align:center\">Have you a nice day!<br></div>\r\n"
				+ "                                        </div>\r\n"
				+ "                                        <div style=\"text-align:left\">\r\n"
				+ "                                            <div style=\"font-family:Roboto-Regular,Helvetica,Arial,sans-serif;color:rgba(0,0,0,0.54);font-size:11px;line-height:18px;padding-top:12px;text-align:center\">\r\n"
				+ "                                                <div>We send you this email notifying you about the status of the subtask.</div>\r\n"
				+ "                                                <div style=\"direction:ltr\">© 2022 Google LLC, <a class=\"m_-6341730908529643193afal\" style=\"font-family:Roboto-Regular,Helvetica,Arial,sans-serif;color:rgba(0,0,0,0.54);font-size:11px;line-height:18px;padding-top:12px;text-align:center\">1600 Amphitheatre Parkway, Mountain View, CA 94043, USA</a></div>\r\n"
				+ "                                            </div>\r\n"
				+ "                                        </div>\r\n" + "                                    </td>\r\n"
				+ "                                    <td width=\"8\" style=\"width:8px\"></td>\r\n"
				+ "                                </tr>\r\n" + "                            </tbody>\r\n"
				+ "                        </table>\r\n" + "                    </td>\r\n" + "                </tr>\r\n"
				+ "                <tr height=\"32\" style=\"height:32px\">\r\n" + "                    <td></td>\r\n"
				+ "                </tr>\r\n" + "            </tbody>\r\n" + "        </table>\r\n" + "    </div>";
		return body;
	}

	public String bodyInviteToSubTask(String titleSubTask, String fullname, String projectName, String taskName,
			String subName, String creator, String time, String content) {
		String body = "\r\n"
				+ "    <div style=\"font-family:proxima-nova,Proxima Nova,sans-serif;padding:0;max-width:600px;margin:0 auto\" class=\"m_4484129935566177621email-container\">\r\n"
				+ "        <table align=\"center\" role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"100%\" style=\"font-family:proxima-nova,Proxima Nova,sans-serif;padding:0;border-spacing:0!important;border-collapse:collapse!important;table-layout:fixed!important;margin:0 auto!important\">\r\n"
				+ "            <tbody>\r\n"
				+ "                <tr style=\"font-family:proxima-nova,Proxima Nova,sans-serif;margin:0;padding:0\">\r\n"
				+ "                    <td class=\"m_4484129935566177621logo m_4484129935566177621bottom-pad-small\" style=\"font-family:proxima-nova,Proxima Nova,sans-serif;margin:0;padding:0;text-align:center;padding-top:36px;padding-left:36px;padding-right:36px;padding-bottom:24px!important\"\r\n"
				+ "                        align=\"center\">\r\n"
				+ "                        <a href=\"https://links.flickr.com/u/click?_t=40ac9f0c38d540238d36950e58265982&amp;_m=5292180a6f25450089ab7043c0993eb7&amp;_e=sh1Wat_bGCCJb0NljH6A8RbunejdRkwDTubcznHeEY83ZDsPJkKi4QfBWw0yT9FWSpja3wBoOxH1-auC5LlbfK4UMm1F8acbrkG4LJppjYYWmiwJNkuLdO_acxsm7QJRtK4vTdfVOzTZoI1faBEvnhqPVwixQH-0D4ShUjEmllpoJq4l_p-jWSsjoiFKWYuabEiL3Zv9ei9tQQIDbn9422UBtBgLjPbwlIfcK234CZ_3vLmZ8wiYtDvRYS2JQ4hxR2mknOqxkRg_1lyiS7ri74mk5Jy86NCG1ZoC7fuEI8j_R56yXUy5Wt19vRpyBpwalT6c2oWAi0KOjN5utLm4WA%3D%3D\"\r\n"
				+ "                            style=\"font-family:proxima-nova,Proxima Nova,sans-serif;margin:0;padding:0;text-decoration:none\" target=\"_blank\" data-saferedirecturl=\"https://www.google.com/url?q=https://links.flickr.com/u/click?_t%3D40ac9f0c38d540238d36950e58265982%26_m%3D5292180a6f25450089ab7043c0993eb7%26_e%3Dsh1Wat_bGCCJb0NljH6A8RbunejdRkwDTubcznHeEY83ZDsPJkKi4QfBWw0yT9FWSpja3wBoOxH1-auC5LlbfK4UMm1F8acbrkG4LJppjYYWmiwJNkuLdO_acxsm7QJRtK4vTdfVOzTZoI1faBEvnhqPVwixQH-0D4ShUjEmllpoJq4l_p-jWSsjoiFKWYuabEiL3Zv9ei9tQQIDbn9422UBtBgLjPbwlIfcK234CZ_3vLmZ8wiYtDvRYS2JQ4hxR2mknOqxkRg_1lyiS7ri74mk5Jy86NCG1ZoC7fuEI8j_R56yXUy5Wt19vRpyBpwalT6c2oWAi0KOjN5utLm4WA%253D%253D&amp;source=gmail&amp;ust=1672034921353000&amp;usg=AOvVaw0EYXPcoZ4Hfo-tHnc7GxKA\">\r\n"
				+ "                            <img width=\"86\" alt=\"\" style=\"font-family:proxima-nova,Proxima Nova,sans-serif;margin:0;padding:0;border-width:0\" src=\"\" class=\"CToWUd\" data-bit=\"iit\"> </a>\r\n"
				+ "                    </td>\r\n" + "                </tr>\r\n"
				+ "                <tr style=\"font-family:proxima-nova,Proxima Nova,sans-serif;margin:0;padding:0\">\r\n"
				+ "                    <td style=\"font-family:proxima-nova,Proxima Nova,sans-serif;margin:0;padding:0;background-color:#ffffff;border-radius:4px\" bgcolor=\"#FFFFFF\">\r\n"
				+ "                        <table role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"100%\" style=\"font-family:proxima-nova,Proxima Nova,sans-serif;padding:0;border-spacing:0!important;border-collapse:collapse!important;table-layout:fixed!important;margin:0 auto!important\">\r\n"
				+ "                            <tbody>\r\n"
				+ "                                <tr style=\"font-family:proxima-nova,Proxima Nova,sans-serif;margin:0;padding:0\">\r\n"
				+ "                                    <td style=\"font-family:proxima-nova,Proxima Nova,sans-serif;margin:0;padding:0;border-width:1px;border-color:#222222\">\r\n"
				+ "                                        <a href=\"https://links.flickr.com/u/click?_t=40ac9f0c38d540238d36950e58265982&amp;_m=5292180a6f25450089ab7043c0993eb7&amp;_e=sh1Wat_bGCCJb0NljH6A8aqqhgW7mWPmJVjd5UyBPrt3ABJiObqOMd4ohCLy3-YZdJXiyiKM0vOOuZlYje_5OVudnKtRhjs3uoOIT1Vf_Q1ebIMm8iq8KsuG7fNRs4pHFdeS2w3rLyWVGYjORbyyL2Z0FOt_-IIgZihLQFpyEpQrdqoUTNpAZFVwTosQHTIzatg0URAGI7YfHI8ZUlahgfHlZEgetvggLaAY7ZoU_nbaZK75a3IFslqgEslNf4iXFRF5tbVG3d4o3OKiuBYtK6tiZL7GHqJyxH6IaFaNzcePlzOoHUbpDdsRYXrZX1ADhITXqDr6bQ86vBhf3B3PNQ%3D%3D\"\r\n"
				+ "                                            style=\"font-family:proxima-nova,Proxima Nova,sans-serif;margin:0;padding:0;text-decoration:none\" target=\"_blank\" data-saferedirecturl=\"https://www.google.com/url?q=https://links.flickr.com/u/click?_t%3D40ac9f0c38d540238d36950e58265982%26_m%3D5292180a6f25450089ab7043c0993eb7%26_e%3Dsh1Wat_bGCCJb0NljH6A8aqqhgW7mWPmJVjd5UyBPrt3ABJiObqOMd4ohCLy3-YZdJXiyiKM0vOOuZlYje_5OVudnKtRhjs3uoOIT1Vf_Q1ebIMm8iq8KsuG7fNRs4pHFdeS2w3rLyWVGYjORbyyL2Z0FOt_-IIgZihLQFpyEpQrdqoUTNpAZFVwTosQHTIzatg0URAGI7YfHI8ZUlahgfHlZEgetvggLaAY7ZoU_nbaZK75a3IFslqgEslNf4iXFRF5tbVG3d4o3OKiuBYtK6tiZL7GHqJyxH6IaFaNzcePlzOoHUbpDdsRYXrZX1ADhITXqDr6bQ86vBhf3B3PNQ%253D%253D&amp;source=gmail&amp;ust=1672034921353000&amp;usg=AOvVaw2bJXZTa9LP1tMJ8FWC6K7Q\">\r\n"
				+ "                                            <img alt=\"\" border=\"0\" color=\"#333333\" style=\"font-family:proxima-nova,Proxima Nova,sans-serif;padding:0;width:100%;max-width:648px;height:auto;background:#ffffff;margin:auto;display:block\" class=\"m_4484129935566177621g-img CToWUd\" src=\"https://f5-zpcloud.zdn.vn/6154930491962742012/1b68547cfc53240d7d42.jpg\"\r\n"
				+ "                                                data-bit=\"iit\"> </a>\r\n"
				+ "                                    </td>\r\n" + "                                </tr>\r\n"
				+ "                                <tr style=\"font-family:proxima-nova,Proxima Nova,sans-serif;margin:0;padding:0;background-color:#ffffff\" bgcolor=\"#FFFFFF\">\r\n"
				+ "                                    <td class=\"m_4484129935566177621content-box m_4484129935566177621top-pad-big\" style=\"font-family:proxima-nova,Proxima Nova,sans-serif;margin:0;padding:0;text-align:left;padding-left:72px;padding-right:72px;padding-bottom:0;display:block;padding-top:48px!important\"\r\n"
				+ "                                        align=\"left\">\r\n"
				+ "                                        <h3 style=\"padding:0;font-family:proxima-nova,Proxima Nova,sans-serif;font-weight:500;margin:0 0 24px 0;line-height:44px;text-align:center!important;font-size:40px!important\">"
				+ titleSubTask + "</h3>\r\n" + "                                    </td>\r\n"
				+ "                                </tr>\r\n"
				+ "                                <tr style=\"font-family:proxima-nova,Proxima Nova,sans-serif;margin:0;padding:0\">\r\n"
				+ "                                    <td class=\"m_4484129935566177621border-pad\" style=\"font-family:proxima-nova,Proxima Nova,sans-serif;margin:0;padding:0;padding-top:0px;padding-bottom:18px;padding-right:72px;padding-left:72px;background-color:#ffffff\" bgcolor=\"#FFFFFF\">\r\n"
				+ "                                        <table width=\"100%\" style=\"font-family:proxima-nova,Proxima Nova,sans-serif;padding:0;color:#f3f5f6;border-spacing:0!important;border-collapse:collapse!important;table-layout:fixed!important;margin:0 auto!important\">\r\n"
				+ "                                            <tbody style=\"font-family:proxima-nova,Proxima Nova,sans-serif;margin:0;padding:0\">\r\n"
				+ "                                                <tr style=\"font-family:proxima-nova,Proxima Nova,sans-serif;margin:0;padding:0\">\r\n"
				+ "                                                    <td bgcolor=\"#DDE2EB\" height=\"1\" style=\"font-family:proxima-nova,Proxima Nova,sans-serif;margin:0;padding:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0\"> </td>\r\n"
				+ "                                                </tr>\r\n"
				+ "                                            </tbody>\r\n"
				+ "                                        </table>\r\n"
				+ "                                    </td>\r\n" + "                                </tr>\r\n"
				+ "                            </tbody>\r\n" + "                        </table>\r\n"
				+ "                    </td>\r\n" + "                </tr>\r\n"
				+ "                <tr style=\"font-family:proxima-nova,Proxima Nova,sans-serif;margin:0;padding:0;background-color:#ffffff\" bgcolor=\"#FFFFFF\">\r\n"
				+ "                    <td class=\"m_4484129935566177621content-box m_4484129935566177621top-pad-small\" style=\"font-family:proxima-nova,Proxima Nova,sans-serif;margin:0;padding:0;text-align:left;padding-left:72px;padding-right:72px;padding-bottom:0;display:block;padding-top:24px!important\"\r\n"
				+ "                        align=\"left\">\r\n"
				+ "                        <p style=\"padding:0;font-family:proxima-nova,Proxima Nova,sans-serif;margin:0 0 24px 0;color:#212124;text-align:center;line-height:10px;font-weight:700;font-size:22px!important\">Hi, "
				+ fullname + "</p>\r\n"
				+ "                        <p style=\"padding:0;font-family:proxima-nova,Proxima Nova,sans-serif;margin:0 0 24px 0;color:#212124;text-align:left;line-height:10px;font-weight:500;font-size:18px!important\"><b>From project:</b> "
				+ projectName + "</p>\r\n"
				+ "                        <p style=\"padding:0;font-family:proxima-nova,Proxima Nova,sans-serif;margin:0 0 24px 0;color:#212124;text-align:left;line-height:10px;font-weight:500;font-size:18px!important\"><b>Task:</b> "
				+ taskName + "</p>\r\n"
				+ "                        <p style=\"padding:0;font-family:proxima-nova,Proxima Nova,sans-serif;margin:0 0 24px 0;color:#212124;text-align:left;line-height:10px;font-weight:500;font-size:18px!important\"><b>Subtask:</b> "
				+ subName + "</p>\r\n"
				+ "                        <p style=\"padding:0;font-family:proxima-nova,Proxima Nova,sans-serif;margin:0 0 24px 0;color:#212124;text-align:left;line-height:10px;font-weight:500;font-size:18px!important\"><b>Creator:</b> "
				+ creator + "</p>\r\n"
				+ "                        <p style=\"padding:0;font-family:proxima-nova,Proxima Nova,sans-serif;margin:0 0 24px 0;color:#212124;text-align:left;line-height:10px;font-weight:500;font-size:18px!important\"><b>Time:</b> "
				+ time + "</p>\r\n"
				+ "                        <p style=\"padding:0;font-family:proxima-nova,Proxima Nova,sans-serif;margin:0 0 24px 0;color:#212124;text-align:center;line-height:10px;font-weight:500;font-size:18px!important\"><b>Content:</b> "
				+ content + "</p>\r\n"
				+ "                        <p style=\"padding:0;font-family:proxima-nova,Proxima Nova,sans-serif;margin:0 0 24px 0;color:#959599;text-align:center;line-height:15px;font-weight:500;font-size:14px!important\">Have you a nice day!</p>\r\n"
				+ "                    </td>\r\n" + "\r\n" + "                </tr>\r\n" + "\r\n" + "\r\n"
				+ "            </tbody>\r\n" + "        </table>\r\n"
				+ "        <table style=\"font-family:proxima-nova,Proxima Nova,sans-serif;padding:0;border-spacing:0!important;border-collapse:collapse!important;table-layout:fixed!important;margin:0 auto!important\">\r\n"
				+ "            <tbody style=\"font-family:proxima-nova,Proxima Nova,sans-serif;margin:0;padding:0\"> </tbody>\r\n"
				+ "        </table>\r\n"
				+ "        <table align=\"center\" role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"100%\" style=\"margin:auto\">\r\n"
				+ "            <tbody>\r\n" + "                <tr>\r\n"
				+ "                    <td style=\"text-align:center;padding-top:0px;padding-bottom:0px;padding-right:16px;padding-left:16px\">\r\n"
				+ "                        <center>\r\n"
				+ "                            <table width=\"280\" align=\"center\" style=\"border-spacing:0;color:#4a4a4a;font-family:proxima-nova,Proxima Nova,sans-serif,Arial,Helvetica,sans-serif\">\r\n"
				+ "                                <tbody>\r\n" + "                                    <tr>\r\n"
				+ "                                        <td width=\"40\" style=\"text-align:center;padding-top:16px;padding-bottom:16px;padding-right:16px;padding-left:16px\">\r\n"
				+ "                                            <a style=\"color:#ee6a56;text-decoration:underline\" href=\"https://links.flickr.com/u/click?_t=40ac9f0c38d540238d36950e58265982&amp;_m=5292180a6f25450089ab7043c0993eb7&amp;_e=OCLYnPaoF6HdqNgkJ0Xre7RlIPzr_XuENaEyaars5pcj4q9gaxrI5epyx9qjfYaoYshjHo70uYDTRHd3jleH7Q1x7oxD3Y_oUqJt1RrRS5wb-xrXx4DDvolYpTGc-qVjEV-qamDZyK1IwOLq5GcKFpE-n-YuLwwnCJf8POrbo2GlaOhzCpxZALg50nb3Y_GRBuvlY0Eu1ss0mPtAhgXryINWifME8T-NuZQPa-DxncwWS1abgHZ8ubaRCMw-1roPdmicIEvDFnsQ0-T1DvsgcuE5QKudCwEfCPGahy1nK7Slxkur4Tg0yvzBpIaczwWn\"\r\n"
				+ "                                                target=\"_blank\" data-saferedirecturl=\"https://www.google.com/url?q=https://links.flickr.com/u/click?_t%3D40ac9f0c38d540238d36950e58265982%26_m%3D5292180a6f25450089ab7043c0993eb7%26_e%3DOCLYnPaoF6HdqNgkJ0Xre7RlIPzr_XuENaEyaars5pcj4q9gaxrI5epyx9qjfYaoYshjHo70uYDTRHd3jleH7Q1x7oxD3Y_oUqJt1RrRS5wb-xrXx4DDvolYpTGc-qVjEV-qamDZyK1IwOLq5GcKFpE-n-YuLwwnCJf8POrbo2GlaOhzCpxZALg50nb3Y_GRBuvlY0Eu1ss0mPtAhgXryINWifME8T-NuZQPa-DxncwWS1abgHZ8ubaRCMw-1roPdmicIEvDFnsQ0-T1DvsgcuE5QKudCwEfCPGahy1nK7Slxkur4Tg0yvzBpIaczwWn&amp;source=gmail&amp;ust=1672034921353000&amp;usg=AOvVaw0oIRiNcEX8B-eWyCrNPTzi\"><img height=\"30\" alt=\"Flickr\" style=\"border-width:0\" src=\"https://ci4.googleusercontent.com/proxy/-HQPont8kEAno_poIc7yvmuW7sHyff7yq6zmWhAXPXYbgKhbqHfjiBBGfqc8XSr1hbaf-xxEEnuv08LPrdNzjfMWghp2PwFtsM7Ojlklp0a3IXSYjVJOQkPzYp5PBfMPHwUAxNE1E3_0qaRP_J00sV0wvQ=s0-d-e1-ft#https://photos.smugmug.com/Email/Flickr-Marketing/Footer-Icons/i-vrwDWLd/0/92bf6c39/O/Flickr.png\"\r\n"
				+ "                                                    class=\"CToWUd\" data-bit=\"iit\"></a>\r\n"
				+ "                                        </td>\r\n"
				+ "                                        <td width=\"40\" style=\"text-align:center;padding-top:16px;padding-bottom:16px;padding-right:16px;padding-left:16px\">\r\n"
				+ "                                            <a style=\"color:#ee6a56;text-decoration:underline\" href=\"https://links.flickr.com/u/click?_t=40ac9f0c38d540238d36950e58265982&amp;_m=5292180a6f25450089ab7043c0993eb7&amp;_e=sh1Wat_bGCCJb0NljH6A8aWvq1w0Idrk2MsQZZNjn2GatXTqe08TbxAymxLW_KldOtcpcXZhTq-W8S3RJI4tvhv_1hBbpSzsuw7jUSetAeqYOTGP114MHz7B8JCNs72_3L9LYrsY-qKsnvaFDNdDBvG3f-bMhxNdYlCNXxbBLcQMQUNsJQxZ-L-ELoCQrJbGG22W7n8KPPVZNRB-8T1ItqruhjFIdMfiRB7B6K0arxFbkStnaUo0ia1gU7B9_KaZhyH91K0RezpBVsKAjhLlZIMClZLoFyJXlur7Bfs1ny8rNq-z_u5_w5RTj8ZIXIBJ\"\r\n"
				+ "                                                target=\"_blank\" data-saferedirecturl=\"https://www.google.com/url?q=https://links.flickr.com/u/click?_t%3D40ac9f0c38d540238d36950e58265982%26_m%3D5292180a6f25450089ab7043c0993eb7%26_e%3Dsh1Wat_bGCCJb0NljH6A8aWvq1w0Idrk2MsQZZNjn2GatXTqe08TbxAymxLW_KldOtcpcXZhTq-W8S3RJI4tvhv_1hBbpSzsuw7jUSetAeqYOTGP114MHz7B8JCNs72_3L9LYrsY-qKsnvaFDNdDBvG3f-bMhxNdYlCNXxbBLcQMQUNsJQxZ-L-ELoCQrJbGG22W7n8KPPVZNRB-8T1ItqruhjFIdMfiRB7B6K0arxFbkStnaUo0ia1gU7B9_KaZhyH91K0RezpBVsKAjhLlZIMClZLoFyJXlur7Bfs1ny8rNq-z_u5_w5RTj8ZIXIBJ&amp;source=gmail&amp;ust=1672034921353000&amp;usg=AOvVaw3LeftZF8GmMYqfvzB-3Uq_\"><img width=\"30\" height=\"30\" alt=\"Facebook\" style=\"border-width:0\" src=\"https://ci6.googleusercontent.com/proxy/z5G-T5CUVQMNMWyneRf6TdI9G1v7xsb1Das9CpmwZT0N2TcXMcFpNYizksdiQ4SsA5iS1GMVZ3cQAdGcd4e_CyrPqyblfKHZmfLl7vhi5OJ7q1rSR3stcQQ9OqUwpvR7SqMaGRtq6MxPE_qNykkLIx0S02iA=s0-d-e1-ft#https://photos.smugmug.com/Email/Flickr-Marketing/Footer-Icons/i-TVCQ2Pm/0/4bfbcd4f/O/Facebook.png\"\r\n"
				+ "                                                    class=\"CToWUd\" data-bit=\"iit\"></a>\r\n"
				+ "                                        </td>\r\n"
				+ "                                        <td width=\"40\" style=\"text-align:center;padding-top:16px;padding-bottom:16px;padding-right:16px;padding-left:16px\">\r\n"
				+ "                                            <a style=\"color:#ee6a56;text-decoration:underline\" href=\"https://links.flickr.com/u/click?_t=40ac9f0c38d540238d36950e58265982&amp;_m=5292180a6f25450089ab7043c0993eb7&amp;_e=oOTn-FKd58-xvF3X0VgYobVe8LvaoeZ3bqje5UBFeElboBfRWgGMKT4PPPYHT8I23t89sSU1qq8cmT1Odfyg-8No0_ceNJi8-DTKJj6R0nMPHZ6BUZCjLEwi4w2gixB4vHTP-PMXu1HkOQh88AdDC2MFgYBcYgOHE6m0Q8lH3DuuSa7McW3QIR7p3qh1sLMaSGNqMNtnn5J8PllDLYtpUYUcOaLgv_J-JZxz3f4Qjyyve2uKKtiQgQR_ZGogfRrMdoYEgYNOMgzP2hJ17eaWwk4H-zbFNeV4I5jRKAn-G-S0yfr5IDF83PkxXH9-1MHV\"\r\n"
				+ "                                                target=\"_blank\" data-saferedirecturl=\"https://www.google.com/url?q=https://links.flickr.com/u/click?_t%3D40ac9f0c38d540238d36950e58265982%26_m%3D5292180a6f25450089ab7043c0993eb7%26_e%3DoOTn-FKd58-xvF3X0VgYobVe8LvaoeZ3bqje5UBFeElboBfRWgGMKT4PPPYHT8I23t89sSU1qq8cmT1Odfyg-8No0_ceNJi8-DTKJj6R0nMPHZ6BUZCjLEwi4w2gixB4vHTP-PMXu1HkOQh88AdDC2MFgYBcYgOHE6m0Q8lH3DuuSa7McW3QIR7p3qh1sLMaSGNqMNtnn5J8PllDLYtpUYUcOaLgv_J-JZxz3f4Qjyyve2uKKtiQgQR_ZGogfRrMdoYEgYNOMgzP2hJ17eaWwk4H-zbFNeV4I5jRKAn-G-S0yfr5IDF83PkxXH9-1MHV&amp;source=gmail&amp;ust=1672034921353000&amp;usg=AOvVaw0-QPjjI0hzrqvTSPAgD8bV\"><img width=\"30\" height=\"30\" alt=\"Twitter\" style=\"border-width:0\" src=\"https://ci4.googleusercontent.com/proxy/SSH4njbLcLupdYHT-UDKL2l6mxvBu1I4BJYOHKp3bJcmluXSuyqYkEm_hqFrfKr79UAj2hgjYLDvB3rDekB2-9UoIiCXjIoQNA-jqyebxh00kwrPTXrTuWG4RlhDvKSgHqjEGxcbq7XbxUOiocy8T-QdhSI=s0-d-e1-ft#https://photos.smugmug.com/Email/Flickr-Marketing/Footer-Icons/i-Vq8BBrS/0/8fbd432b/O/Twitter.png\"\r\n"
				+ "                                                    class=\"CToWUd\" data-bit=\"iit\"></a>\r\n"
				+ "                                        </td>\r\n"
				+ "                                        <td width=\"40\" style=\"text-align:center;padding-top:16px;padding-bottom:16px;padding-right:16px;padding-left:16px\">\r\n"
				+ "                                            <a style=\"color:#ee6a56;text-decoration:underline\" href=\"https://links.flickr.com/u/click?_t=40ac9f0c38d540238d36950e58265982&amp;_m=5292180a6f25450089ab7043c0993eb7&amp;_e=sh1Wat_bGCCJb0NljH6A8e5fA4gyWcAO6pl3wa0swzdG8XiqmGydZE29tNa1738o2ywIhbXxgt-w2ShlDI4WsEiqY8yDMo3NtCyb5-8lcVuuaSjRrRC5M1B1H6VxbSPjoowau5ctZbSNzvyMuCBEorZhdBa4Ma_5PNdCBsv8jhQF1vArSDr2UN2XJGiCxU_FH6Agjez45nmePIQHWmdnFUARFXKAWSL2aygvLR9o1RSSII0aib3cHVom0c4QlyWKrVgFaxOpgblfbbedphnqpMBkmBwyyDf9HRX2yZAOdB6BOLpbJnhxM8mFCF2meuZj\"\r\n"
				+ "                                                target=\"_blank\" data-saferedirecturl=\"https://www.google.com/url?q=https://links.flickr.com/u/click?_t%3D40ac9f0c38d540238d36950e58265982%26_m%3D5292180a6f25450089ab7043c0993eb7%26_e%3Dsh1Wat_bGCCJb0NljH6A8e5fA4gyWcAO6pl3wa0swzdG8XiqmGydZE29tNa1738o2ywIhbXxgt-w2ShlDI4WsEiqY8yDMo3NtCyb5-8lcVuuaSjRrRC5M1B1H6VxbSPjoowau5ctZbSNzvyMuCBEorZhdBa4Ma_5PNdCBsv8jhQF1vArSDr2UN2XJGiCxU_FH6Agjez45nmePIQHWmdnFUARFXKAWSL2aygvLR9o1RSSII0aib3cHVom0c4QlyWKrVgFaxOpgblfbbedphnqpMBkmBwyyDf9HRX2yZAOdB6BOLpbJnhxM8mFCF2meuZj&amp;source=gmail&amp;ust=1672034921353000&amp;usg=AOvVaw0c6pM8WA67PoGkQn9U4-TD\"><img width=\"30\" height=\"30\" alt=\"Instagram\" style=\"border-width:0\" src=\"https://ci3.googleusercontent.com/proxy/C4SKC8hikNtU_HPNpWDK9VQxtWtzzs9c5kZefJBIoRi4hdoK7drqxruhXYyjub0rDpPLIhMaBDpNBAD0Ie7ufOU8e9Si9diQ4VzYXmWITM2fWA6oGQE0edhqfgyCX-Rxl4YIuFQkNgR2sGaL6i1nd9GcS753Kg=s0-d-e1-ft#https://photos.smugmug.com/Email/Flickr-Marketing/Footer-Icons/i-Qz44Bgp/0/47dd5a73/O/Instagram.png\"\r\n"
				+ "                                                    class=\"CToWUd\" data-bit=\"iit\"></a>\r\n"
				+ "                                        </td>\r\n" + "                                    </tr>\r\n"
				+ "                                </tbody>\r\n" + "                            </table>\r\n"
				+ "                        </center>\r\n" + "                    </td>\r\n"
				+ "                </tr>\r\n" + "            </tbody>\r\n" + "        </table>\r\n"
				+ "        <table style=\"width:100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\r\n"
				+ "            <tbody>\r\n" + "                <tr>\r\n"
				+ "                    <td align=\"center\">\r\n"
				+ "                        <div class=\"m_4484129935566177621footer-section\">\r\n"
				+ "                            <p class=\"m_4484129935566177621legal\" style=\"color:#888888;font-size:11px!important\">Your use of Flickr is subject to the <a href=\"https://links.flickr.com/u/click?_t=40ac9f0c38d540238d36950e58265982&amp;_m=5292180a6f25450089ab7043c0993eb7&amp;_e=sh1Wat_bGCCJb0NljH6A8eph7fYQr2LdnMOD3ltbTwOHWszxD16AT1qihbtNOTy2EyQsipKF5eGAF7-NbI5CVHDR4cSkumsoZ1toTlUTo04Rlrp9whAs0snMfepp1yGTiOGozmKDHdlFXw6MSbhApBGhfLibK0gCS-qnq-VYlG9oOz6l4Z7SPfMO6J8HXzqAIbpE9qzd6-otPC_m3QlOv2r92aUmBktOPZKMguOw5fr9tDFTUslR5tM4ON6hmF988jpf8pgIFWlrUGJPEDsOBTZrpID68B5bLtFH6IxvBwzZIoPbOg6aEQ66Of6fCf2z\"\r\n"
				+ "                                    style=\"color:#888888;font-size:11px\" target=\"_blank\" data-saferedirecturl=\"https://www.google.com/url?q=https://links.flickr.com/u/click?_t%3D40ac9f0c38d540238d36950e58265982%26_m%3D5292180a6f25450089ab7043c0993eb7%26_e%3Dsh1Wat_bGCCJb0NljH6A8eph7fYQr2LdnMOD3ltbTwOHWszxD16AT1qihbtNOTy2EyQsipKF5eGAF7-NbI5CVHDR4cSkumsoZ1toTlUTo04Rlrp9whAs0snMfepp1yGTiOGozmKDHdlFXw6MSbhApBGhfLibK0gCS-qnq-VYlG9oOz6l4Z7SPfMO6J8HXzqAIbpE9qzd6-otPC_m3QlOv2r92aUmBktOPZKMguOw5fr9tDFTUslR5tM4ON6hmF988jpf8pgIFWlrUGJPEDsOBTZrpID68B5bLtFH6IxvBwzZIoPbOg6aEQ66Of6fCf2z&amp;source=gmail&amp;ust=1672034921353000&amp;usg=AOvVaw1ZMkMJdhU6cRW34I9Oqsp6\">Flickr Terms &amp; Conditions of Use</a>                                and <a style=\"text-decoration:underline;color:#888888;font-size:11px\" href=\"https://links.flickr.com/u/click?_t=40ac9f0c38d540238d36950e58265982&amp;_m=5292180a6f25450089ab7043c0993eb7&amp;_e=sh1Wat_bGCCJb0NljH6A8eph7fYQr2LdnMOD3ltbTwNyl58hfVjpP3cSTbFdo4ZMp3CeNw8HK1bDKIrCBBgt-UGa-R2qsYxj2PRd4XnBCEILVZsR_SBZe4seDg8FstSSWTRU86l9f4u9MLYhJefsvoRP8px4R02tYZvx70SD-1Tm16WTAhu_e1uwHX7R78_Xz3vu6vcvWF3mwgWJ4iAlkqbkYMS6lt0WNPi0aH-6vq3RgGloyDabHdquJ1s61z85RWZ6H5JrZYrg7VknUYduxNzmZcuE8lbkzjjhzXsbhuTRNTKPoKtK1bByw4POwGPoe3Fqmgs9sgxC10diFck5LA%3D%3D\"\r\n"
				+ "                                    target=\"_blank\" data-saferedirecturl=\"https://www.google.com/url?q=https://links.flickr.com/u/click?_t%3D40ac9f0c38d540238d36950e58265982%26_m%3D5292180a6f25450089ab7043c0993eb7%26_e%3Dsh1Wat_bGCCJb0NljH6A8eph7fYQr2LdnMOD3ltbTwNyl58hfVjpP3cSTbFdo4ZMp3CeNw8HK1bDKIrCBBgt-UGa-R2qsYxj2PRd4XnBCEILVZsR_SBZe4seDg8FstSSWTRU86l9f4u9MLYhJefsvoRP8px4R02tYZvx70SD-1Tm16WTAhu_e1uwHX7R78_Xz3vu6vcvWF3mwgWJ4iAlkqbkYMS6lt0WNPi0aH-6vq3RgGloyDabHdquJ1s61z85RWZ6H5JrZYrg7VknUYduxNzmZcuE8lbkzjjhzXsbhuTRNTKPoKtK1bByw4POwGPoe3Fqmgs9sgxC10diFck5LA%253D%253D&amp;source=gmail&amp;ust=1672034921353000&amp;usg=AOvVaw3LwCDhLcIIlVPcAvTL_2OT\">Community Guidelines</a>                                </p>\r\n"
				+ "                            <p class=\"m_4484129935566177621legal\" style=\"color:#888888;font-size:11px!important\"> Note: this message is in reference to <a href=\"https://links.flickr.com/u/click?_t=40ac9f0c38d540238d36950e58265982&amp;_m=5292180a6f25450089ab7043c0993eb7&amp;_e=sh1Wat_bGCCJb0NljH6A8RbunejdRkwDTubcznHeEY9Vx1m9YHzZ54Qa0Y2KhygUaHyfjS6hzXnM6tInkwgZq5dpQTxjL3u4trfYW1fjoNNAwu68PFUruOZ0IyO01wx2gPmwjLQ39Awje4aGgeRLkN12FU1sORfvEAcum211tkCtTf0G9gxWUuGNAzNMLR2fTNVJzz8cq7g7CWEvDvtofn7pKiv2_qL4661N_1HMwMi8sBqg737xf6lmrUwjYQwWJtsJ4oMkY9pP98LtMf_vEmHRZjdSUSJy9gtDSd2ATvpObq2oxQfv78sxmCYZ5SXiOa3kQOlueioZsmU7987Y3w%3D%3D\"\r\n"
				+ "                                    style=\"text-decoration:underline;color:#888888;font-size:11px\" target=\"_blank\" data-saferedirecturl=\"https://www.google.com/url?q=https://links.flickr.com/u/click?_t%3D40ac9f0c38d540238d36950e58265982%26_m%3D5292180a6f25450089ab7043c0993eb7%26_e%3Dsh1Wat_bGCCJb0NljH6A8RbunejdRkwDTubcznHeEY9Vx1m9YHzZ54Qa0Y2KhygUaHyfjS6hzXnM6tInkwgZq5dpQTxjL3u4trfYW1fjoNNAwu68PFUruOZ0IyO01wx2gPmwjLQ39Awje4aGgeRLkN12FU1sORfvEAcum211tkCtTf0G9gxWUuGNAzNMLR2fTNVJzz8cq7g7CWEvDvtofn7pKiv2_qL4661N_1HMwMi8sBqg737xf6lmrUwjYQwWJtsJ4oMkY9pP98LtMf_vEmHRZjdSUSJy9gtDSd2ATvpObq2oxQfv78sxmCYZ5SXiOa3kQOlueioZsmU7987Y3w%253D%253D&amp;source=gmail&amp;ust=1672034921353000&amp;usg=AOvVaw0rXuBHpayfwQJolxAnOoG7\"> Flickr account 196577269@N06</a>.</p>\r\n"
				+ "                            <p class=\"m_4484129935566177621legal\" style=\"color:#888888;font-size:11px\"><a href=\"https://links.flickr.com/e/evib?_t=40ac9f0c38d540238d36950e58265982&amp;_m=5292180a6f25450089ab7043c0993eb7&amp;_e=8V-rYe3FSMwg-pnEFEBqf6lURZkXBrv6D2Dr00iJHz7QOA0eWQob-S3RVmvND0VO\" style=\"color:#888888;font-size:11px\"\r\n"
				+ "                                    target=\"_blank\" data-saferedirecturl=\"https://www.google.com/url?q=https://links.flickr.com/e/evib?_t%3D40ac9f0c38d540238d36950e58265982%26_m%3D5292180a6f25450089ab7043c0993eb7%26_e%3D8V-rYe3FSMwg-pnEFEBqf6lURZkXBrv6D2Dr00iJHz7QOA0eWQob-S3RVmvND0VO&amp;source=gmail&amp;ust=1672034921353000&amp;usg=AOvVaw1N9PJJ4KUM-E1CrbqZwh7o\">View in browser</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;\r\n"
				+ "                                <a href=\"https://links.flickr.com/e/encryptedUnsubscribe?_r=40ac9f0c38d540238d36950e58265982&amp;_s=5292180a6f25450089ab7043c0993eb7&amp;_t=8V-rYe3FSMwg-pnEFEBqf6lURZkXBrv6D2Dr00iJHz7hxp0HcHk77mH71D_fTd_3fg8j26CfMrbOf7cWOUl3FC9CrCsLWOAV9EubmN9TZN8PxVkl7bXXYKvkxL5dI-hz\"\r\n"
				+ "                                    style=\"color:#888888;font-size:11px\" target=\"_blank\" data-saferedirecturl=\"https://www.google.com/url?q=https://links.flickr.com/e/encryptedUnsubscribe?_r%3D40ac9f0c38d540238d36950e58265982%26_s%3D5292180a6f25450089ab7043c0993eb7%26_t%3D8V-rYe3FSMwg-pnEFEBqf6lURZkXBrv6D2Dr00iJHz7hxp0HcHk77mH71D_fTd_3fg8j26CfMrbOf7cWOUl3FC9CrCsLWOAV9EubmN9TZN8PxVkl7bXXYKvkxL5dI-hz&amp;source=gmail&amp;ust=1672034921353000&amp;usg=AOvVaw0tRgc6qhwTtwYUDeZDrCw3\">Unsubscribe</a>\r\n"
				+ "                            </p>\r\n"
				+ "                            <p class=\"m_4484129935566177621legal\" style=\"font-family:sofia-pro,sans-serif!important;color:#888888!important;font-size:11px!important\">© 2022 Flickr, <span style=\"font-family:sofia-pro,sans-serif!important;color:#888888!important;font-size:11px!important\">P.O. Box 390123, Mountain View, CA 94039</span> </p>\r\n"
				+ "                        </div>\r\n" + "                    </td>\r\n" + "                </tr>\r\n"
				+ "            </tbody>\r\n" + "        </table>\r\n" + "    </div>";
		return body;
	}

	public String bodyDealine(String fullname,String projectName,String taskName,String creator,String time,String content) {
		String body="\r\n"
				+ "    <div style=\"padding:0;margin:0;background:#efefef\">\r\n"
				+ "        <table style=\"height:100%;width:100%;background-color:#efefef\" align=\"center\">\r\n"
				+ "            <tbody>\r\n"
				+ "                <tr>\r\n"
				+ "                    <td id=\"m_756421175332475651dbody\" style=\"width:100%;height:100%;padding-top:30px;padding-bottom:30px;background-color:#efefef\" valign=\"top\">\r\n"
				+ "\r\n"
				+ "                        <table style=\"max-width:600px;box-sizing:border-box;width:100%;margin:0px auto\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" align=\"center\">\r\n"
				+ "                            <tbody>\r\n"
				+ "                                <tr>\r\n"
				+ "                                    <td style=\"background-color:#ffffff;box-sizing:border-box;font-size:0px;text-align:center\" valign=\"top\" align=\"center\">\r\n"
				+ "                                        <div class=\"m_756421175332475651layer_2\" style=\"max-width:600px;display:inline-block;vertical-align:top;width:100%\">\r\n"
				+ "                                            <table style=\"border-collapse:collapse;width:100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\r\n"
				+ "                                                <tbody>\r\n"
				+ "                                                    <tr>\r\n"
				+ "                                                        <td style=\"padding:0px;box-sizing:border-box;text-align:center\" valign=\"top\">\r\n"
				+ "                                                            <a href=\"http://email.nicepage.com/tracking/click?d=VVYbLzpOzsm7pGuuO7GLcsy3YTXl3Pl9QafuDnjQ1vMSvJa-brg4wDuHKenMSOmR3hppo3UzIxJcQY_-Y-FA9bmmQtmLjPqpEvba-Jz3tzN0qciLzsuP0-5TbkvvVgadLTCEvGh5wOT0r6AOFJJ5JbA2_7Wkhp3uwsSyXHfNHFoX93myB_oNZv23x_JeOlPlhzdN0sgxjSskHsgjQsMXsHrKAf06eAsSzywODUc4jNyL0\"\r\n"
				+ "                                                                target=\"_blank\" data-saferedirecturl=\"https://www.google.com/url?q=http://email.nicepage.com/tracking/click?d%3DVVYbLzpOzsm7pGuuO7GLcsy3YTXl3Pl9QafuDnjQ1vMSvJa-brg4wDuHKenMSOmR3hppo3UzIxJcQY_-Y-FA9bmmQtmLjPqpEvba-Jz3tzN0qciLzsuP0-5TbkvvVgadLTCEvGh5wOT0r6AOFJJ5JbA2_7Wkhp3uwsSyXHfNHFoX93myB_oNZv23x_JeOlPlhzdN0sgxjSskHsgjQsMXsHrKAf06eAsSzywODUc4jNyL0&amp;source=gmail&amp;ust=1672042412803000&amp;usg=AOvVaw21XwrQL1h0GRZAXA-eKZU-\"><img style=\"border-width:0px;border-style:none;max-width:600px;width:100%\" src=\"https://f8-zpcloud.zdn.vn/7183635177170730947/5f44c60f5921817fd830.jpg\" alt=\"Merry Christmas and Happy New Year 2023!\"\r\n"
				+ "                                                                    width=\"600\" class=\"CToWUd\" data-bit=\"iit\"></a>\r\n"
				+ "                                                        </td>\r\n"
				+ "                                                    </tr>\r\n"
				+ "                                                </tbody>\r\n"
				+ "                                            </table>\r\n"
				+ "                                        </div>\r\n"
				+ "                                    </td>\r\n"
				+ "                                </tr>\r\n"
				+ "                                <tr>\r\n"
				+ "                                    <td style=\"background-color:#ffffff;box-sizing:border-box;font-size:0px;text-align:center\" valign=\"top\" align=\"center\">\r\n"
				+ "                                        <div class=\"m_756421175332475651layer_2\" style=\"max-width:600px;display:inline-block;vertical-align:top;width:100%\">\r\n"
				+ "                                            <table style=\"border-collapse:collapse;width:100%\" cellspacing=\"0\" border=\"0\">\r\n"
				+ "                                                <tbody>\r\n"
				+ "                                                    <tr>\r\n"
				+ "                                                        <td style=\"padding:20px;text-align:left;color:#333333;font-size:16px;font-family:Helvetica,Arial,sans-serif;direction:ltr;box-sizing:border-box\" valign=\"top\">\r\n"
				+ "                                                            <p style=\"line-height:1.5em;margin:0px;padding:0px\"><b>Dear</b>, "+fullname+"</p>\r\n"
				+ "                                                            <p style=\"line-height:1.5em;margin:0px;padding:0px\"><br></p>\r\n"
				+ "                                                            <p style=\"line-height:1.5em;margin:0px;padding:0px;text-align: center;\">Merry Christmas and Happy New Year 2023!</p>\r\n"
				+ "                                                            <p style=\"line-height:1.5em;margin:0px;padding:0px\"><br></p>\r\n"
				+ "                                                            <p style=\"line-height:1.5em;margin:0px;padding:0px\"><b>From Project</b>: "+projectName+"</p>\r\n"
				+ "                                                            <p style=\"margin:0px;padding:0px \"><br></p>\r\n"
				+ "                                                            <p style=\"line-height:1.5em;margin:0px;padding:0px \"><b>Task:</b> "+taskName+"</p>\r\n"
				+ "                                                            <p style=\"margin:0px;padding:0px \"><br></p>\r\n"
				+ "                                                            <p style=\"line-height:1.5em;margin:0px;padding:0px \"><b>Creator:</b>"+creator+"</p>\r\n"
				+ "                                                            <p style=\"margin:0px;padding:0px \"><br></p>\r\n"
				+ "                                                            <p style=\"line-height:1.5em;margin:0px;padding:0px;color: red;\"><b style=\"color: #333333;\">Time:</b> "+time+"</p>\r\n"
				+ "                                                            <p style=\"margin:0px;padding:0px \"><br></p>\r\n"
				+ "                                                            <p style=\"line-height:1.5em;margin:0px;padding:0px \"><b>Content:</b> content </p>\r\n"
				+ "                                                            <p style=\"line-height:1em;margin:0px;padding:0px ;text-align: center; font-size: 14px;\"><b>Have you a nice day!</p>\r\n"
				+ "                                                        </td>\r\n"
				+ "                                                    </tr>\r\n"
				+ "                                                </tbody>\r\n"
				+ "                                            </table>\r\n"
				+ "                                        </div>\r\n"
				+ "                                    </td>\r\n"
				+ "                                </tr>\r\n"
				+ "                                <tr>\r\n"
				+ "                                    <td style=\"background-color:#ffffff;box-sizing:border-box;font-size:0px;text-align:center \" valign=\"top \" align=\"center \">\r\n"
				+ "                                        <div class=\"m_756421175332475651layer_2 \" style=\"max-width:600px;display:inline-block;vertical-align:top;width:100% \">\r\n"
				+ "                                            <table style=\"border-collapse:collapse;width:100% \" cellspacing=\"0 \" cellpadding=\"0 \" border=\"0 \">\r\n"
				+ "                                                <tbody>\r\n"
				+ "                                                    <tr>\r\n"
				+ "                                                        <td style=\"padding:0px;box-sizing:border-box;text-align:center \" valign=\"top \">\r\n"
				+ "                                                            <a href=\"http://email.nicepage.com/tracking/click?d=Aul0OGTAIiC9IR0AyCZ2GVbkkO53IM_c3ILD-ttOd4zcAAOaehhDLJsyYJSqjWWRwmm8lwZIbKlczfVq1HS4atE4uNRBio-92TotJM0OuYvtCKDlKCPzQ5NIipsl_b4LMzqtMH1g5neOrZHLKFR9wy6WLfXUnl7a8vxrJCKeS40MM_zrP9S0PI5554Id0OWbkoyyvrla9-YoiUN4GDGQwULgQz1AE6pfGfvKucfnIyZTxlfYSAFVn-UJKJ7wSsYQ4Q2 \"\r\n"
				+ "                                                                target=\"_blank \" data-saferedirecturl=\"https://www.google.com/url?q=http://email.nicepage.com/tracking/click?d%3DAul0OGTAIiC9IR0AyCZ2GVbkkO53IM_c3ILD-ttOd4zcAAOaehhDLJsyYJSqjWWRwmm8lwZIbKlczfVq1HS4atE4uNRBio-92TotJM0OuYvtCKDlKCPzQ5NIipsl_b4LMzqtMH1g5neOrZHLKFR9wy6WLfXUnl7a8vxrJCKeS40MM_zrP9S0PI5554Id0OWbkoyyvrla9-YoiUN4GDGQwULgQz1AE6pfGfvKucfnIyZTxlfYSAFVn-UJKJ7wSsYQ4Q2&amp;source=gmail&amp;ust=1672042412803000&amp;usg=AOvVaw3tLX0l5Gf5vcNr0ijOY2WW\r\n"
				+ "                                                                \"><img src=\"https://ci4.googleusercontent.com/proxy/Lu_XwHICneQO3iORrOtNR6cAHf2__SEFYRuiweSiSOrVUzpDOeyoRC2jbBxpkpRGSJ7UcX4_EayzY7eRmx3Tf0Z4EyZN03ISx5owOtzBpgSg4FKhEmN5enm6Jf2aAvF34pGWIs7eDWn1pRQmyFROgV3xQw=s0-d-e1-ft#https://api.elasticemail.com/userfile/b4857811-d92e-456e-8cbd-0131acf89a92/Nicepage-Logotype.png \"\r\n"
				+ "                                                                    alt=\"Nicepage: design websites in minutes. \" style=\"border-width:0px;border-style:none;max-width:0px;width:100% \" width=\"0 \" class=\"CToWUd \" data-bit=\"iit \"></a>\r\n"
				+ "                                                        </td>\r\n"
				+ "                                                    </tr>\r\n"
				+ "                                                </tbody>\r\n"
				+ "                                            </table>\r\n"
				+ "                                        </div>\r\n"
				+ "                                    </td>\r\n"
				+ "                                </tr>\r\n"
				+ "                                <tr>\r\n"
				+ "                                    <td style=\"background-color:#ffffff;box-sizing:border-box;font-size:0px;text-align:center \" valign=\"top \" align=\"center \">\r\n"
				+ "                                        <div class=\"m_756421175332475651layer_2 \" style=\"max-width:600px;display:inline-block;vertical-align:top;width:100% \">\r\n"
				+ "                                            <table style=\"border-collapse:collapse;width:100% \" cellspacing=\"0 \" cellpadding=\"0 \" border=\"0 \">\r\n"
				+ "                                                <tbody>\r\n"
				+ "                                                    <tr>\r\n"
				+ "                                                        <td style=\"padding:10px;box-sizing:border-box;text-align:center \" valign=\"top \">\r\n"
				+ "                                                            <a href=\"http://email.nicepage.com/tracking/click?d=VVYbLzpOzsm7pGuuO7GLcsy3YTXl3Pl9QafuDnjQ1vMSvJa-brg4wDuHKenMSOmR3hppo3UzIxJcQY_-Y-FA9bmmQtmLjPqpEvba-Jz3tzOyf-z-eNKS6fMkQ1qJTvnEQCXczU9bcv8kmq5R3D0Lvx-yjF1rZ65FfG0G3tNWNEYS0pNWKax-1zRvalBCS9F5XRW2zcx_5pior6skTk4JsAfPpfValVvxpXgI01iZ7C9e0 \"\r\n"
				+ "                                                                target=\"_blank \" data-saferedirecturl=\"https://www.google.com/url?q=http://email.nicepage.com/tracking/click?d%3DVVYbLzpOzsm7pGuuO7GLcsy3YTXl3Pl9QafuDnjQ1vMSvJa-brg4wDuHKenMSOmR3hppo3UzIxJcQY_-Y-FA9bmmQtmLjPqpEvba-Jz3tzOyf-z-eNKS6fMkQ1qJTvnEQCXczU9bcv8kmq5R3D0Lvx-yjF1rZ65FfG0G3tNWNEYS0pNWKax-1zRvalBCS9F5XRW2zcx_5pior6skTk4JsAfPpfValVvxpXgI01iZ7C9e0&amp;source=gmail&amp;ust=1672042412803000&amp;usg=AOvVaw3DM5onPTxkZfme7d15lT9y\r\n"
				+ "                                                                \"><img style=\"border-width:0px;border-style:none;max-width:200px;width:100% \" src=\"https://f7-zpcloud.zdn.vn/4413739648967792034/7dc7a6a46d8bb5d5ec9a.jpg\" alt=\"Merry Christmas and Happy New Year 2022! \"\r\n"
				+ "                                                                    width=\"148 \" class=\"CToWUd \" data-bit=\"iit \"></a>\r\n"
				+ "                                                        </td>\r\n"
				+ "                                                    </tr>\r\n"
				+ "                                                </tbody>\r\n"
				+ "                                            </table>\r\n"
				+ "                                        </div>\r\n"
				+ "                                    </td>\r\n"
				+ "                                </tr>\r\n"
				+ "                                <tr>\r\n"
				+ "                                    <td style=\"background-color:#efefef;box-sizing:border-box;font-size:0px;text-align:center \" valign=\"top \" align=\"center \">\r\n"
				+ "                                        <div class=\"m_756421175332475651layer_2 \" style=\"max-width:600px;display:inline-block;vertical-align:top;width:100% \">\r\n"
				+ "                                            <table style=\"border-collapse:collapse;width:100% \" cellspacing=\"0 \" cellpadding=\"0 \" border=\"0 \">\r\n"
				+ "                                                <tbody>\r\n"
				+ "                                                    <tr>\r\n"
				+ "                                                        <td style=\"padding:10px;text-align:left;color:#333333;font-size:16px;font-family:Helvetica,Arial,sans-serif;direction:ltr;box-sizing:border-box \" valign=\"top \">\r\n"
				+ "                                                            <p style=\"text-align:center;font-size:11px;margin:0px;padding:0px \"> If you no longer wish to receive mail from us, you can\r\n"
				+ "                                                                <a href=\"http://email.nicepage.com/tracking/unsubscribe?d=EoXRVZQ7REPeORmd3NBrK9tx4chMMzVbvdIgvgccfFW6FgAWbovJrnS4J83-kH-EimQNBBuDfaY9fnCjnzW4cnlWKVauHyz28vTnknmZo6QP0 \" style=\"color:#3498db;text-decoration:none\r\n"
				+ "                                                                \" target=\"_blank \" data-saferedirecturl=\"https://www.google.com/url?q=http://email.nicepage.com/tracking/unsubscribe?d%3DEoXRVZQ7REPeORmd3NBrK9tx4chMMzVbvdIgvgccfFW6FgAWbovJrnS4J83-kH-EimQNBBuDfaY9fnCjnzW4cnlWKVauHyz28vTnknmZo6QP0&amp;source=gmail&amp;ust=1672042412804000&amp;usg=AOvVaw3eDp0fCZxj-ZFhryTYLB5C \">unsubscribe</a>\r\n"
				+ "                                                                <br>\r\n"
				+ "                                                                <br>\r\n"
				+ "                                                            </p>\r\n"
				+ "                                                        </td>\r\n"
				+ "                                                    </tr>\r\n"
				+ "                                                </tbody>\r\n"
				+ "                                            </table>\r\n"
				+ "                                        </div>\r\n"
				+ "\r\n"
				+ "                                    </td>\r\n"
				+ "                                </tr>\r\n"
				+ "                            </tbody>\r\n"
				+ "                        </table>\r\n"
				+ "\r\n"
				+ "                    </td>\r\n"
				+ "                </tr>\r\n"
				+ "            </tbody>\r\n"
				+ "        </table>\r\n"
				+ "        <div style=\"text-align:center;background-color:#fff;padding-top:10px;padding-bottom:10px;font-size:8pt;font-family:sans-serif \">\r\n"
				+ "        </div><img src=\"https://f7-zpcloud.zdn.vn/4413739648967792034/7dc7a6a46d8bb5d5ec9a.jpg\" style=\"width:1px;height:1px \" alt=\" \" class=\"CToWUd \" data-bit=\"iit \"></div>";
		return body;
	}
		
	public String openOrCloseProject(String projectName,String sendFrom,String time,String content) {
		String body="  <div style=\"word-spacing:normal;background-color:#f2f2f2\">\r\n"
				+ "        <div style=\"display:none;max-height:0px;overflow:hidden\">Get started with frameworks you love, or import directly from GitHub.</div>\r\n"
				+ "        <div style=\"display:none;max-height:0px;overflow:hidden\">&nbsp;‌&nbsp;‌&nbsp;‌&nbsp;</div>\r\n"
				+ "        <div style=\"background-color:#f2f2f2\">\r\n"
				+ "            <div style=\"margin:0px auto;max-width:600px\">\r\n"
				+ "                <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"width:100%\">\r\n"
				+ "                    <tbody>\r\n"
				+ "                        <tr>\r\n"
				+ "                            <td style=\"direction:ltr;font-size:0px;padding:0px 0 0px 0;padding-bottom:0px;padding-top:0px;text-align:center\">\r\n"
				+ "                                <div class=\"m_-3754985049220612606mj-column-per-100\" style=\"font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%\">\r\n"
				+ "                                    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" width=\"100%\">\r\n"
				+ "                                        <tbody>\r\n"
				+ "                                            <tr>\r\n"
				+ "                                                <td style=\"vertical-align:top;padding:0 0 0 0\">\r\n"
				+ "                                                    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" width=\"100%\">\r\n"
				+ "                                                        <tbody>\r\n"
				+ "                                                            <tr>\r\n"
				+ "                                                                <td align=\"center\" style=\"font-size:0px;padding:30px 25px 30px 25px;padding-top:30px;padding-right:25px;padding-bottom:30px;padding-left:25px;word-break:break-word\">\r\n"
				+ "                                                                    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"border-collapse:collapse;border-spacing:0px\">\r\n"
				+ "                                                                        <tbody>\r\n"
				+ "                                                                            <tr>\r\n"
				+ "                                                                                <td style=\"width:250px\">\r\n"
				+ "                                                                                    <a href=\"\" target=\"_blank\" data-saferedirecturl=\"\">\r\n"
				+ "                                                                                        <img alt=\"Glitch\" src=\"https://f7-zpcloud.zdn.vn/4413739648967792034/7dc7a6a46d8bb5d5ec9a.jpg\" style=\"border:none;display:block;outline:none;text-decoration:none;height:auto;width:100%;font-size:13px\" class=\"CToWUd\" data-bit=\"iit\">\r\n"
				+ "                                                                                    </a>\r\n"
				+ "                                                                                </td>\r\n"
				+ "                                                                            </tr>\r\n"
				+ "                                                                        </tbody>\r\n"
				+ "                                                                    </table>\r\n"
				+ "                                                                </td>\r\n"
				+ "                                                            </tr>\r\n"
				+ "                                                        </tbody>\r\n"
				+ "                                                    </table>\r\n"
				+ "                                                </td>\r\n"
				+ "                                            </tr>\r\n"
				+ "                                        </tbody>\r\n"
				+ "                                    </table>\r\n"
				+ "                                </div>\r\n"
				+ "                            </td>\r\n"
				+ "                        </tr>\r\n"
				+ "                    </tbody>\r\n"
				+ "                </table>\r\n"
				+ "            </div>\r\n"
				+ "            <div style=\"margin:0 auto;max-width:600px\">\r\n"
				+ "                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"width:100%\">\r\n"
				+ "                    <tbody>\r\n"
				+ "                        <tr style=\"vertical-align:top\">\r\n"
				+ "                            <td background=\"https://f7-zpcloud.zdn.vn/4709977809018731607/e969f23d4813904dc902.jpg\" style=\"background: url(https://f7-zpcloud.zdn.vn/4709977809018731607/e969f23d4813904dc902.jpg) no-repeat center bottom/cover;background-position:center bottom;background-repeat:no-repeat;border-radius:5px 5px 0 0;padding:0;vertical-align:top\"\r\n"
				+ "                                height=\"400\">\r\n"
				+ "                                <div style=\"margin:0px auto\">\r\n"
				+ "                                    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"width:100%;margin:0px\">\r\n"
				+ "                                        <tbody>\r\n"
				+ "                                            <tr>\r\n"
				+ "                                                <td>\r\n"
				+ "                                                    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"width:100%;margin:0px\">\r\n"
				+ "\r\n"
				+ "                                                    </table>\r\n"
				+ "                                                </td>\r\n"
				+ "                                            </tr>\r\n"
				+ "                                        </tbody>\r\n"
				+ "                                    </table>\r\n"
				+ "                                </div>\r\n"
				+ "                            </td>\r\n"
				+ "                        </tr>\r\n"
				+ "                    </tbody>\r\n"
				+ "                </table>\r\n"
				+ "            </div>\r\n"
				+ "            <div style=\"background:#ffffff;background-color:#ffffff;margin:0px auto;border-radius:0;max-width:600px\">\r\n"
				+ "                <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"background:#ffffff;background-color:#ffffff;width:100%;border-radius:0\">\r\n"
				+ "                    <tbody>\r\n"
				+ "                        <tr>\r\n"
				+ "                            <td style=\"direction:ltr;font-size:0px;padding:20px 0;text-align:center\">\r\n"
				+ "                                <div class=\"m_-3754985049220612606mj-column-per-100\" style=\"font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%\">\r\n"
				+ "                                    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"vertical-align:top\" width=\"100%\">\r\n"
				+ "                                        <tbody>\r\n"
				+ "                                            <tr>\r\n"
				+ "                                                <td align=\"left\" style=\"font-size:0px;padding:15px 25px 0px 25px;padding-top:15px;padding-right:25px;padding-bottom:0px;padding-left:25px;word-break:break-word\">\r\n"
				+ "                                                    <div style=\"font-family:Arial,sans-serif;font-size:18px;line-height:1;text-align:left;color:#000000\">\r\n"
				+ "                                                        <h1 style=\"line-height:42px;text-align: center;\"><b>Project Notify</b></h1>\r\n"
				+ "                                                    </div>\r\n"
				+ "                                                </td>\r\n"
				+ "                                            </tr>\r\n"
				+ "                                            <tr>\r\n"
				+ "                                                <td align=\"left\" style=\"font-size:0px;padding:0 25px 10px 25px;padding-top:0px;padding-right:25px;padding-bottom:10px;padding-left:25px;word-break:break-word\">\r\n"
				+ "                                                    <div style=\"font-family:Arial,sans-serif;font-size:16px;line-height:25px;text-align:left;color:#333333\"><b>Project: </b>: "+projectName+"</div>\r\n"
				+ "                                                    <div style=\"font-family:Arial,sans-serif;font-size:16px;line-height:25px;text-align:left;color:#333333\"><b>Creator: </b>: "+sendFrom+"</div>\r\n"
				+ "                                                    <div style=\"font-family:Arial,sans-serif;font-size:16px;line-height:25px;text-align:left;color:#333333\"><b>Create date: </b>: "+time+"</div>\r\n"
				+ "                                                    <div style=\"font-family:Arial,sans-serif;font-size:16px;line-height:25px;text-align:left;color:#333333\"><b>Content</b>: "+content+"</div>\r\n"
				+ "                                                    <div style=\"font-family:Arial,sans-serif;font-size:14px;line-height:25px;text-align:center;color:#808080\">Have you a nice day!</div>\r\n"
				+ "                                                </td>\r\n"
				+ "                                            </tr>\r\n"
				+ "                                            <tr>\r\n"
				+ "                                                <td align=\"center\" style=\"background:#ffffff;font-size:0px;padding:20px 30px 20px 30px;padding-top:20px;padding-right:25px;padding-bottom:20px;padding-left:25px;word-break:break-word\">\r\n"
				+ "                                                    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"border-collapse:separate;line-height:100%\">\r\n"
				+ "                                                        <tbody>\r\n"
				+ "                                                            <tr>\r\n"
				+ "                                                                <td align=\"center\" bgcolor=\"#FFFFFF\" role=\"presentation\" style=\"border:2px solid #000000;border-radius:5px;background:#ffffff\" valign=\"middle\">\r\n"
				+ "                                                                    <a href=\"linkproject\" style=\"display:inline-block;background:#ffffff;color:#000000;font-family:Fira Code,Arial,sans-serif;font-size:14px;font-weight:bold;line-height:120%;margin:0;text-decoration:none;text-transform:none;padding:10px 25px;border-radius:5px\"\r\n"
				+ "                                                                        target=\"_blank\" data-saferedirecturl=\"\">\r\n"
				+ "                                                                        <img src=\"https://ci5.googleusercontent.com/proxy/fOK99TduKL9fhNLGLHMeOvBOe-IVctcqYm3e-m24RBM0Tirrkug5hSiLexq1dEAXvNcZflgyJsFqMtcGS3zaFXlGykTMZ7tbt7zKPK02pIfR6zvOyDdB3-GizsLqEqtBB8LM1w=s0-d-e1-ft#https://cdn.glitch.com/605e2a51-d45f-4d87-a285-9410ad350515/email-emoji-1f6e0.png\"\r\n"
				+ "                                                                            width=\"15px\" class=\"CToWUd\" data-bit=\"iit\"> Start with us\r\n"
				+ "                                                                    </a>\r\n"
				+ "                                                                </td>\r\n"
				+ "                                                            </tr>\r\n"
				+ "                                                        </tbody>\r\n"
				+ "                                                    </table>\r\n"
				+ "                                                </td>\r\n"
				+ "                                            </tr>\r\n"
				+ "                                        </tbody>\r\n"
				+ "                                    </table>\r\n"
				+ "                                </div>\r\n"
				+ "                            </td>\r\n"
				+ "                        </tr>\r\n"
				+ "                    </tbody>\r\n"
				+ "                </table>\r\n"
				+ "            </div>\r\n"
				+ "            <div style=\"background:#ffffff;background-color:#ffffff;margin:0px auto;border-radius:0 0 5px 5px;max-width:600px\">\r\n"
				+ "                <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"background:#ffffff;background-color:#ffffff;width:100%;border-radius:0 0 5px 5px\">\r\n"
				+ "                    <tbody>\r\n"
				+ "                        <tr>\r\n"
				+ "                            <td style=\"direction:ltr;font-size:0px;padding:0;text-align:center\">\r\n"
				+ "                                <div class=\"m_-3754985049220612606mj-column-per-100\" style=\"font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%\">\r\n"
				+ "                                    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"vertical-align:top\" width=\"100%\">\r\n"
				+ "                                        <tbody>\r\n"
				+ "                                            <tr>\r\n"
				+ "                                                <td align=\"center\" style=\"font-size:0px;padding:0 25px 5px 25px;padding-top:0px;padding-right:25px;padding-bottom:5px;padding-left:25px;word-break:break-word\">\r\n"
				+ "                                                    <div style=\"font-family:Arial,sans-serif;font-size:14px;line-height:24px;text-align:center;color:#4f4f4f\"></div>\r\n"
				+ "                                                </td>\r\n"
				+ "                                            </tr>\r\n"
				+ "                                        </tbody>\r\n"
				+ "                                    </table>\r\n"
				+ "                                </div>\r\n"
				+ "                            </td>\r\n"
				+ "                        </tr>\r\n"
				+ "                    </tbody>\r\n"
				+ "                </table>\r\n"
				+ "            </div>\r\n"
				+ "        </div>\r\n"
				+ "        <img src=\"https://ci5.googleusercontent.com/proxy/OG_nTHLDdItDUuL6CVffUKxr_xZ1Vyukv4E582xIWRRLjnHY49VYbgPQKQ5L5K-ewwcp2dfXImwfZsOn9up0YAl5NHN34iaiNdEa6dhtmyoy2k5wFolh27lN48607JCZRNFcsbNE5vfDNcwo0A42LNLNUO7BqsqWFhp6TwgX5Bk=s0-d-e1-ft#https://email.glitch.com/e/o/eyJlbWFpbF9pZCI6ImRnVHFsd01CQUlxR2pnR0pobzRCQVlTTEtlU21KV0tDOE9uZTNVLXlYUT09In0=\"\r\n"
				+ "            style=\"height:1px!important;max-height:1px!important;max-width:1px!important;width:1px!important;display:none!important\" class=\"CToWUd\" data-bit=\"iit\"></div>";
		return body;
	}
	
}
