package com.nhathanh.until;

import java.util.Date;

public class Utilities {

	public String bodyMail(String code) {
		String body = "\r\n" + "    <td align=\"center\" valign=\"top\">\r\n"
				+ "        <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" width=\"600\" class=\"m_-3947633973872345608container\" style=\"margin:0 auto\">\r\n"
				+ "            <tbody>\r\n" + "\r\n" + "                <tr>\r\n"
				+ "                    <td valign=\"top\" bgcolor=\"#FFFFFF\">\r\n"
				+ "                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" role=\"presentation\" style=\"min-width:100%\" class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                            <tbody>\r\n" + "                                <tr>\r\n"
				+ "                                    <td class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                                        <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" role=\"presentation\">\r\n"
				+ "                                            <tbody>\r\n"
				+ "                                                <tr>\r\n"
				+ "                                                    <td align=\"center\">\r\n"
				+ "                                                        <a href=\"https://click.send.grammarly.com/?qs=75b1430b8b349ea3e3c22838c6e6a2130d1c5ba231e2a643e2b136ed1868611d898c723c1e0c0de3ddbfc4b9b44f11e67d628ff5012fe119c8eec0a176bed6db\" title=\"\" target=\"_blank\" data-saferedirecturl=\"https://www.google.com/url?q=https://click.send.grammarly.com/?qs%3D75b1430b8b349ea3e3c22838c6e6a2130d1c5ba231e2a643e2b136ed1868611d898c723c1e0c0de3ddbfc4b9b44f11e67d628ff5012fe119c8eec0a176bed6db&amp;source=gmail&amp;ust=1666882994848000&amp;usg=AOvVaw23-P_efDAusiaAAZ2jOb9z\"><img src=\"https://ci4.googleusercontent.com/proxy/E6shlpJaJiMKaTChXttcaHjzvJvFLJvQE-0IOFNXccn_gbhfD8mXAd9ZyHgqh4Sl0-4u6Zb8wquBi_OaLsjzATQtXNl8Z110WC8XLFVgRCc8RJVuiFuX3FptNumjxgW_=s0-d-e1-ft#https://image.send.grammarly.com/lib/fe8f12747760017576/m/3/09-2022-hero2.png\"\r\n"
				+ "                                                                alt=\"\" width=\"1200\" style=\"display:block;padding:0px;text-align:center;height:auto;width:100%\" class=\"CToWUd\" data-bit=\"iit\"></a>\r\n"
				+ "                                                    </td>\r\n"
				+ "                                                </tr>\r\n"
				+ "                                            </tbody>\r\n"
				+ "                                        </table>\r\n"
				+ "                                    </td>\r\n" + "                                </tr>\r\n"
				+ "                            </tbody>\r\n" + "                        </table>\r\n"
				+ "                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" role=\"presentation\" style=\"background-color:transparent;min-width:100%\" class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                            <tbody>\r\n" + "                                <tr>\r\n"
				+ "                                    <td style=\"padding:40px 0px\" class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                                        <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
				+ "\r\n" + "                                            <tbody>\r\n"
				+ "                                                <tr>\r\n"
				+ "                                                    <td style=\"text-align:center\" valign=\"middle\">\r\n"
				+ "                                                        <span class=\"m_-3947633973872345608h1\" style=\"color:red\"><h2>Caution: reset your password!</h2>\r\n"
				+ "                                                            You are not remembering your password, our system will reset your password, below is your new password. Be careful with your password!\r\n"
				+ "                                                        </span>\r\n"
				+ "                                                        <br>\r\n"
				+ "                                                        <h3><small>Your password:</small> <b>" + code
				+ "</b></h3>\r\n" + "                                                    </td>\r\n"
				+ "                                                </tr>\r\n"
				+ "                                            </tbody>\r\n"
				+ "                                        </table>\r\n"
				+ "                                    </td>\r\n" + "                                </tr>\r\n"
				+ "                            </tbody>\r\n" + "                        </table>\r\n" + "\r\n"
				+ "                    </td>\r\n" + "                </tr>\r\n" + "            </tbody>\r\n"
				+ "        </table>\r\n" + "\r\n" + "    </td>\r\n" + "    </tr>\r\n" + "    <tr>\r\n"
				+ "        <td valign=\"top\">\r\n"
				+ "            <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" role=\"presentation\" style=\"background-color:transparent;min-width:100%\" class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                <tbody>\r\n" + "                    <tr>\r\n"
				+ "                        <td style=\"padding:0px\" class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                            <table style=\"width:100%\" role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
				+ "                                <tbody>\r\n" + "                                    <tr>\r\n"
				+ "                                        <td>\r\n"
				+ "                                            <table style=\"width:100%\" role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
				+ "                                                <tbody>\r\n"
				+ "                                                    <tr>\r\n"
				+ "                                                        <td style=\"width:100%;padding-bottom:0px\" class=\"m_-3947633973872345608responsive-td\" valign=\"top\">\r\n"
				+ "                                                            <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" role=\"presentation\" style=\"min-width:100%\" class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                                                                <tbody>\r\n"
				+ "                                                                    <tr>\r\n"
				+ "                                                                        <td class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                                                                            <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
				+ "\r\n" + "                                                                                <tbody>\r\n"
				+ "                                                                                    <tr>\r\n"
				+ "                                                                                        <td align=\"center\" valign=\"top\">\r\n"
				+ "                                                                                            <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"m_-3947633973872345608MobileTableWidth\" width=\"87%\">\r\n"
				+ "\r\n"
				+ "                                                                                                <tbody>\r\n"
				+ "                                                                                                    <tr>\r\n"
				+ "                                                                                                        <td height=\"18\" style=\"line-height:18px;font-size:18px\">\r\n"
				+ "                                                                                                            &nbsp;</td>\r\n"
				+ "                                                                                                    </tr>\r\n"
				+ "                                                                                                    <tr>\r\n"
				+ "                                                                                                        <td align=\"center\" valign=\"top\">\r\n"
				+ "                                                                                                            <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
				+ "\r\n"
				+ "                                                                                                                <tbody>\r\n"
				+ "                                                                                                                    <tr>\r\n"
				+ "                                                                                                                        <td align=\"left\" valign=\"top\">\r\n"
				+ "                                                                                                                            <a href=\"https://click.send.grammarly.com/?qs=75b1430b8b349ea34a28110588972af6167efa923b93f3b420361621c5aff903c6339aa9fe8e99511988744202f924db1230d6d7955971d3\" title=\"Facebook\" target=\"_blank\" data-saferedirecturl=\"https://www.google.com/url?q=https://click.send.grammarly.com/?qs%3D75b1430b8b349ea34a28110588972af6167efa923b93f3b420361621c5aff903c6339aa9fe8e99511988744202f924db1230d6d7955971d3&amp;source=gmail&amp;ust=1666882994848000&amp;usg=AOvVaw2ezKLePDWxoSc0-nqu-JQc\"><img alt=\"Facebook\" border=\"0\" src=\"https://ci4.googleusercontent.com/proxy/tpGgbkuez9vOFcjbW9aw75AS2D_Tu4yiIdjQJHo_jvDwcPC4anwxLGIYg8Aa_z5j1FjBS2r7xpYaG_dixO7_X5IhekRC8ilDcMvPh3dpeVoYUv_E3RTtuK1UZ8Tg4bcKTqxV-Y-cY6OUXVs=s0-d-e1-ft#https://image.send.grammarly.com/lib/fe8f12747760017576/m/2/EBS-Facebook_Footer_Icon.png\"\r\n"
				+ "                                                                                                                                    style=\"display:block\" title=\"Facebook\" width=\"11\" class=\"CToWUd\" data-bit=\"iit\"></a>\r\n"
				+ "                                                                                                                        </td>\r\n"
				+ "                                                                                                                        <td align=\"left\" valign=\"top\" width=\"60\">\r\n"
				+ "                                                                                                                        </td>\r\n"
				+ "                                                                                                                        <td align=\"left\" valign=\"top\">\r\n"
				+ "                                                                                                                            <a href=\"https://click.send.grammarly.com/?qs=75b1430b8b349ea3f20cdb999115e019f9d3a50d08ef03af384f61dbec410640080aac5389c04278e119dae7dfe8880a268cb17c9dcd39f7\" title=\"Instagram\" target=\"_blank\" data-saferedirecturl=\"https://www.google.com/url?q=https://click.send.grammarly.com/?qs%3D75b1430b8b349ea3f20cdb999115e019f9d3a50d08ef03af384f61dbec410640080aac5389c04278e119dae7dfe8880a268cb17c9dcd39f7&amp;source=gmail&amp;ust=1666882994849000&amp;usg=AOvVaw38IATCR3ahBYJvykD6BTCr\"><img alt=\"Instagram\" border=\"0\" src=\"https://ci3.googleusercontent.com/proxy/RQxhl0x69mE1_o6JJXlfBKPlMWnsJy5fxzHSu873pkIC_-r0MBeJev_r-b4ZQ0ZJUu2xoMFJExs2uJCqkwbHaWQ8UmcIWX9btvY7DxJydY3UJ7Kg9iwHLCYr5-1van0TrY1mEeY1VW4Kvylp=s0-d-e1-ft#https://image.send.grammarly.com/lib/fe8f12747760017576/m/2/EBS-Instagram_Footer_Icon.png\"\r\n"
				+ "                                                                                                                                    style=\"display:block\" title=\"Instagram\" width=\"25\" class=\"CToWUd\" data-bit=\"iit\"></a>\r\n"
				+ "                                                                                                                        </td>\r\n"
				+ "                                                                                                                        <td align=\"left\" valign=\"top\" width=\"58\">\r\n"
				+ "                                                                                                                        </td>\r\n"
				+ "                                                                                                                        <td align=\"left\" valign=\"top\">\r\n"
				+ "                                                                                                                            <a href=\"https://click.send.grammarly.com/?qs=75b1430b8b349ea3d6f594e5fde9a19a67861598fc11974c1ac020ac10062bac5073c537a3a1a49dfe7a691a1cb8e8237d9aac745279261a\" title=\"LinkedIn\" target=\"_blank\" data-saferedirecturl=\"https://www.google.com/url?q=https://click.send.grammarly.com/?qs%3D75b1430b8b349ea3d6f594e5fde9a19a67861598fc11974c1ac020ac10062bac5073c537a3a1a49dfe7a691a1cb8e8237d9aac745279261a&amp;source=gmail&amp;ust=1666882994849000&amp;usg=AOvVaw3lBRudvZlhTRTq0j5Esxi5\"><img alt=\"LinkedIn\" border=\"0\" src=\"https://ci5.googleusercontent.com/proxy/5rvd2QxJv7gaNC75cgB2pFHtxO6W8tifEUwv-_HxpUATrBlF_I4NhHGbQz2Xz4BnVyF3HvC9T3wvh8Cvq7T5GPm72skeQSw9Gj1UQpY8Xbmh77XFdH9O83vVsDBJ4cRKSNCIWZFozmdxxcw=s0-d-e1-ft#https://image.send.grammarly.com/lib/fe8f12747760017576/m/2/EBS-LinkedIn_Footer_Icon.png\"\r\n"
				+ "                                                                                                                                    style=\"display:block\" title=\"LinkedIn\" width=\"18\" class=\"CToWUd\" data-bit=\"iit\"></a>\r\n"
				+ "                                                                                                                        </td>\r\n"
				+ "                                                                                                                        <td align=\"left\" valign=\"top\" width=\"58\">\r\n"
				+ "                                                                                                                        </td>\r\n"
				+ "                                                                                                                        <td align=\"left\" valign=\"top\">\r\n"
				+ "                                                                                                                            <a href=\"https://click.send.grammarly.com/?qs=75b1430b8b349ea335d4747778cea1bbfb8db49f7fb7b14b7075b2b2ad6fb0ed9456efeb782a9b69300565c8df714e6ce34343f161810569\" title=\"Twitter\" target=\"_blank\" data-saferedirecturl=\"https://www.google.com/url?q=https://click.send.grammarly.com/?qs%3D75b1430b8b349ea335d4747778cea1bbfb8db49f7fb7b14b7075b2b2ad6fb0ed9456efeb782a9b69300565c8df714e6ce34343f161810569&amp;source=gmail&amp;ust=1666882994849000&amp;usg=AOvVaw0V-sH5WTgELF02c13X5CJl\"><img alt=\"Twitter\" border=\"0\" src=\"https://ci4.googleusercontent.com/proxy/JKHlljn73jyNuOOj1VX3VS070F56L_MiFqBQpJXuzThJruhYqNJY2tX1WyxAAFvbhtQbYhM7A-zJGh3Er_JTZZojPXDH4iV-zeDXUTBlnoIJPjiDbxogvrUocasqjZVc4KLRgBnrvhaUGQ=s0-d-e1-ft#https://image.send.grammarly.com/lib/fe8f12747760017576/m/2/EBS-Twitter_Footer_Icon.png\"\r\n"
				+ "                                                                                                                                    style=\"display:block\" title=\"Twitter\" width=\"22\" class=\"CToWUd\" data-bit=\"iit\"></a>\r\n"
				+ "                                                                                                                        </td>\r\n"
				+ "                                                                                                                    </tr>\r\n"
				+ "                                                                                                                </tbody>\r\n"
				+ "                                                                                                            </table>\r\n"
				+ "                                                                                                        </td>\r\n"
				+ "                                                                                                    </tr>\r\n"
				+ "                                                                                                    <tr>\r\n"
				+ "                                                                                                        <td height=\"25\" style=\"line-height:25px;font-size:25px\">\r\n"
				+ "                                                                                                            &nbsp;</td>\r\n"
				+ "                                                                                                    </tr>\r\n"
				+ "                                                                                                    <tr>\r\n"
				+ "                                                                                                        <td bgcolor=\"#C6CBDE\" height=\"1\" style=\"line-height:1px;font-size:1px\">\r\n"
				+ "                                                                                                            &nbsp;</td>\r\n"
				+ "                                                                                                    </tr>\r\n"
				+ "                                                                                                    <tr>\r\n"
				+ "                                                                                                        <td height=\"25\" style=\"line-height:25px;font-size:25px\">\r\n"
				+ "                                                                                                            &nbsp;</td>\r\n"
				+ "                                                                                                    </tr>\r\n"
				+ "                                                                                                    <tr>\r\n"
				+ "\r\n" + "\r\n"
				+ "                                                                                                    </tr>\r\n"
				+ "                                                                                                    <tr>\r\n"
				+ "                                                                                                        <td height=\"25\" style=\"line-height:25px;font-size:25px\">\r\n"
				+ "                                                                                                            &nbsp;</td>\r\n"
				+ "                                                                                                    </tr>\r\n"
				+ "                                                                                                    <tr>\r\n"
				+ "                                                                                                        <td style=\"font-weight:400;line-height:20px;font-size:14px;text-align:center;color:#4d536e\" valign=\"top\">\r\n"
				+ "                                                                                                            *This offer is active until 9/22/2022 and cannot be combined with other offers, discounts, or applied to prior purchases. <a href=\"https://click.send.grammarly.com/?qs=75b1430b8b349ea32b26c08b7fae0049c189564d9406f1a6cdc52fc58cd0a739d689f47fc2d36f99d6d557eb71c280df4ebdb6cff0252bb212f7d756f4ad0e46\"\r\n"
				+ "                                                                                                                style=\"text-decoration:none\" title=\"Additional terms\" target=\"_blank\" data-saferedirecturl=\"https://www.google.com/url?q=https://click.send.grammarly.com/?qs%3D75b1430b8b349ea32b26c08b7fae0049c189564d9406f1a6cdc52fc58cd0a739d689f47fc2d36f99d6d557eb71c280df4ebdb6cff0252bb212f7d756f4ad0e46&amp;source=gmail&amp;ust=1666882994849000&amp;usg=AOvVaw1Z8--l7NVr_Y0COmwDLiSv\">Additional terms</a>\r\n"
				+ "                                                                                                            <a href=\"https://click.send.grammarly.com/?qs=75b1430b8b349ea3728110c24108e8d108474e5f6bfa746b2163beb9fe00d2b880ade01e11fbf175a9a1cb094611636a6372d9a1729f434ad1ac8fce9509dbd0\" style=\"text-decoration:none\" title=\"Additional terms apply\" target=\"_blank\"\r\n"
				+ "                                                                                                                data-saferedirecturl=\"https://www.google.com/url?q=https://click.send.grammarly.com/?qs%3D75b1430b8b349ea3728110c24108e8d108474e5f6bfa746b2163beb9fe00d2b880ade01e11fbf175a9a1cb094611636a6372d9a1729f434ad1ac8fce9509dbd0&amp;source=gmail&amp;ust=1666882994849000&amp;usg=AOvVaw2aoeSg6c82LlbR5LUxgQBY\">\r\n"
				+ "                                                                                                            </a>apply.<br>\r\n"
				+ "                                                                                                            <br> You received this offer for Grammarly Premium because you are currently opted in to receive them via your preference settings. You may adjust\r\n"
				+ "                                                                                                            your preferences at any time by clicking the link above.<br>\r\n"
				+ "                                                                                                            <br> This offer is not valid for Grammarly Business purchases.<br>\r\n"
				+ "                                                                                                            <br> © 2022 Grammarly, Inc. 548 Market St. #35410, San Francisco, CA 94104</td>\r\n"
				+ "                                                                                                    </tr>\r\n"
				+ "                                                                                                </tbody>\r\n"
				+ "                                                                                            </table>\r\n"
				+ "                                                                                        </td>\r\n"
				+ "                                                                                    </tr>\r\n"
				+ "                                                                                </tbody>\r\n"
				+ "                                                                            </table> <img border=\"0\" height=\"1\" src=\"https://ci4.googleusercontent.com/proxy/r702lz0nwsVJ6LYPTPXyXzBvXaAAj4KUnEmViGVtOXfBSJMk7HlfOUV9DlnGDm2WDMYCxxx36PLyZfhVhdaGSXglp53TuV9br8dbYa0L9EQQIJO7YOROvX1hMiKns6_K8RgXMTVsU8fETsup_iAhnOsG422W338tKfXbmL6IRtv1-WqNClxolOLX2wXHN_fZqcMZhudgrHmpE4VtM4_rj9d3uoTqJLyir43qZ1vkBzQK6DaXoCrx7P0LNZN41Tg=s0-d-e1-ft#https://gnar.grammarly.com/email-pixel?userId=&amp;email=vothanhnha744@gmail.com&amp;templateName=2022-09-18_GC-LCM-FRE-ALL-CUST-ACT-PROM_Exp2_2X&amp;sentTime=9/18/2022%208:52:07%20AM\"\r\n"
				+ "                                                                                style=\"display:none\" width=\"1\" class=\"CToWUd\" data-bit=\"iit\" jslog=\"138226; u014N:xr6bB; 53:W2ZhbHNlLDJd\"></td>\r\n"
				+ "                                                                    </tr>\r\n"
				+ "                                                                </tbody>\r\n"
				+ "                                                            </table>\r\n"
				+ "                                                        </td>\r\n"
				+ "                                                    </tr>\r\n"
				+ "                                                </tbody>\r\n"
				+ "                                            </table>\r\n"
				+ "                                        </td>\r\n" + "                                    </tr>\r\n"
				+ "                                    <tr>\r\n" + "                                        <td>\r\n"
				+ "                                            <table style=\"width:100%\" role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
				+ "                                                <tbody>\r\n"
				+ "                                                    <tr>\r\n"
				+ "                                                        <td style=\"width:100%;padding-top:0px\" class=\"m_-3947633973872345608responsive-td\" valign=\"top\">\r\n"
				+ "                                                            <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" role=\"presentation\" style=\"min-width:100%\" class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                                                                <tbody>\r\n"
				+ "                                                                    <tr>\r\n"
				+ "                                                                        <td class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                                                                            <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\r\n"
				+ "\r\n" + "                                                                                <tbody>\r\n"
				+ "                                                                                    <tr>\r\n"
				+ "                                                                                        <td style=\"line-height:64px;font-size:64px\" height=\"64\">\r\n"
				+ "                                                                                            &nbsp;</td>\r\n"
				+ "                                                                                    </tr>\r\n"
				+ "                                                                                </tbody>\r\n"
				+ "                                                                            </table>\r\n"
				+ "                                                                        </td>\r\n"
				+ "                                                                    </tr>\r\n"
				+ "                                                                </tbody>\r\n"
				+ "                                                            </table>\r\n"
				+ "                                                        </td>\r\n"
				+ "                                                    </tr>\r\n"
				+ "                                                </tbody>\r\n"
				+ "                                            </table>\r\n"
				+ "                                        </td>\r\n" + "                                    </tr>\r\n"
				+ "                                </tbody>\r\n" + "                            </table>\r\n"
				+ "                        </td>\r\n" + "                    </tr>\r\n" + "                </tbody>\r\n"
				+ "            </table>\r\n" + "        </td>\r\n" + "    </tr>\r\n" + "    </tbody>\r\n"
				+ "    </table>\r\n" + "    </td>";
		return body;
	}

	public String bodyMail1(String nameProject, String fullname, String topic, String startDate, String link,
			String content) {
		String body = " <td align=\"center\" valign=\"top\">\r\n"
				+ "        <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" width=\"600\" class=\"m_-3947633973872345608container\" style=\"margin:0 auto\">\r\n"
				+ "            <tbody>\r\n" + "                <tr>\r\n"
				+ "                    <td valign=\"top\" bgcolor=\"#FFFFFF\">\r\n"
				+ "                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" role=\"presentation\" style=\"min-width:100%\" class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                            <tbody>\r\n" + "                                <tr>\r\n"
				+ "                                    <td class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                                        <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" role=\"presentation\">\r\n"
				+ "                                            <tbody>\r\n"
				+ "                                                <tr>\r\n"
				+ "                                                    <td align=\"center\">\r\n"
				+ "                                                        <a href=\"#\" title=\"\" target=\"_blank\" data-saferedirecturl=\"https://assets-global.website-files.com/62196607bf1b46c300301846/627120768c6e8b7f8e368a2a_hugo-illustration-calendar-extension.png\"><img src=\"https://assets-global.website-files.com/62196607bf1b46c300301846/627120768c6e8b7f8e368a2a_hugo-illustration-calendar-extension.png\" alt=\"\" width=\"1200\" style=\"display:block;padding:0px;text-align:center;height:auto;width:100%\"\r\n"
				+ "                                                                class=\"CToWUd\" data-bit=\"iit\"></a>\r\n"
				+ "                                                    </td>\r\n"
				+ "                                                </tr>\r\n"
				+ "                                            </tbody>\r\n"
				+ "                                        </table>\r\n"
				+ "                                    </td>\r\n" + "                                </tr>\r\n"
				+ "                            </tbody>\r\n" + "                        </table>\r\n"
				+ "                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" role=\"presentation\" style=\"background-color:transparent;min-width:100%\" class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                            <tbody>\r\n" + "                                <tr>\r\n"
				+ "                                    <td style=\"padding:40px 0px\" class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                                        <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
				+ "                                            <tbody>\r\n"
				+ "                                                <tr>\r\n"
				+ "                                                    <h2 style=\"color: #4d536e;text-align: center;\">The system PMF sends to you a message</h2>\r\n"
				+ "                                                </tr>\r\n"
				+ "                                                <h3 style=\"color: #4d536e;\">Hi, " + fullname
				+ "</h3>\r\n"
				+ "                                                <h3 style=\"color: #4d536e;\">You have a meeting from : "
				+ nameProject + "</h3>\r\n"
				+ "                                                <h3 style=\"color: #4d536e;\"><small>Topic meeting: </small> <b style=\"color: gray;\">\r\n"
				+ "         " + topic + " </b></h3>\r\n"
				+ "                                                <h3 style=\"color:#4d536e\"><small>The time start: </small> <b style=\"color: gray;\">\r\n"
				+ "         " + startDate + " </b></h3>\r\n"
				+ "                                                <span style=\"color:rgb(10, 10, 177)\">Link: </span>\r\n"
				+ "                                                <a href=\"" + link + "\" target=\"_blank \">  "
				+ link + " </a>\r\n" + "                                                <tr>\r\n"
				+ "                                                    <td style=\"text-align:center\" valign=\"middle\">\r\n"
				+ "                                                        <h3 style=\"color: #4d536e;\">Reminding your meeting (content)</h3>\r\n"
				+ "                                                        <span class=\"m_-3947633973872345608h1\" style=\"color:#4d536e\">\r\n"
				+ "                                                                       " + content + " \r\n"
				+ "                                                        </span>\r\n"
				+ "                                                    </td>\r\n"
				+ "                                                    <br>\r\n"
				+ "                                                </tr>\r\n"
				+ "                                            </tbody>\r\n"
				+ "                                        </table>\r\n"
				+ "                                    </td>\r\n" + "                                </tr>\r\n"
				+ "                            </tbody>\r\n" + "                        </table>\r\n"
				+ "                    </td>\r\n" + "                </tr>\r\n" + "            </tbody>\r\n"
				+ "        </table>\r\n" + "    </td>\r\n" + "    </tr>\r\n" + "    <tr>\r\n"
				+ "        <td valign=\"top\">\r\n"
				+ "            <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" role=\"presentation\" style=\"background-color:transparent;min-width:100%\" class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                <tbody>\r\n" + "                    <tr>\r\n"
				+ "                        <td style=\"padding:0px\" class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                            <table style=\"width:100%\" role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
				+ "                                <tbody>\r\n" + "                                    <tr>\r\n"
				+ "                                        <td>\r\n"
				+ "                                            <table style=\"width:100%\" role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
				+ "                                                <tbody>\r\n"
				+ "                                                    <tr>\r\n"
				+ "                                                        <td style=\"width:100%;padding-bottom:0px\" class=\"m_-3947633973872345608responsive-td\" valign=\"top\">\r\n"
				+ "                                                            <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" role=\"presentation\" style=\"min-width:100%\" class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                                                                <tbody>\r\n"
				+ "                                                                    <tr>\r\n"
				+ "                                                                        <td class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                                                                            <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
				+ "                                                                                <tbody>\r\n"
				+ "                                                                                    <tr>\r\n"
				+ "                                                                                        <td align=\"center\" valign=\"top\">\r\n"
				+ "                                                                                            <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"m_-3947633973872345608MobileTableWidth\" width=\"87%\">\r\n"
				+ "\r\n"
				+ "                                                                                                <tbody>\r\n"
				+ "\r\n"
				+ "                                                                                                    <tr>\r\n"
				+ "                                                                                                        <td style=\"font-weight:400;line-height:20px;font-size:14px;text-align:center;color:#4d536e\" valign=\"top\">\r\n"
				+ "                                                                                                            *This offer is active until 9/22/2022 and cannot be combined with other offers, discounts, or applied to prior purchases. <a href=\"https://click.send.grammarly.com/?qs=75b1430b8b349ea32b26c08b7fae0049c189564d9406f1a6cdc52fc58cd0a739d689f47fc2d36f99d6d557eb71c280df4ebdb6cff0252bb212f7d756f4ad0e46\"\r\n"
				+ "                                                                                                                style=\"text-decoration:none\" title=\"Additional terms\" target=\"_blank\" data-saferedirecturl=\"https://www.google.com/url?q=https://click.send.grammarly.com/?qs%3D75b1430b8b349ea32b26c08b7fae0049c189564d9406f1a6cdc52fc58cd0a739d689f47fc2d36f99d6d557eb71c280df4ebdb6cff0252bb212f7d756f4ad0e46&amp;source=gmail&amp;ust=1666882994849000&amp;usg=AOvVaw1Z8--l7NVr_Y0COmwDLiSv\">Additional terms</a>\r\n"
				+ "                                                                                                            <a href=\"https://click.send.grammarly.com/?qs=75b1430b8b349ea3728110c24108e8d108474e5f6bfa746b2163beb9fe00d2b880ade01e11fbf175a9a1cb094611636a6372d9a1729f434ad1ac8fce9509dbd0\" style=\"text-decoration:none\" title=\"Additional terms apply\" target=\"_blank\"\r\n"
				+ "                                                                                                                data-saferedirecturl=\"https://www.google.com/url?q=https://click.send.grammarly.com/?qs%3D75b1430b8b349ea3728110c24108e8d108474e5f6bfa746b2163beb9fe00d2b880ade01e11fbf175a9a1cb094611636a6372d9a1729f434ad1ac8fce9509dbd0&amp;source=gmail&amp;ust=1666882994849000&amp;usg=AOvVaw2aoeSg6c82LlbR5LUxgQBY\">\r\n"
				+ "                                                                                                            </a>apply.<br>\r\n"
				+ "                                                                                                            <br> You received this offer for Grammarly Premium because you are currently opted in to receive them via your preference settings. You may adjust\r\n"
				+ "                                                                                                            your preferences at any time by clicking the link above.<br>\r\n"
				+ "                                                                                                            <br> This offer is not valid for Grammarly Business purchases.<br>\r\n"
				+ "                                                                                                            <br> © 2022 Grammarly, Inc. 548 Market St. #35410, San Francisco, CA 94104</td>\r\n"
				+ "                                                                                                    </tr>\r\n"
				+ "                                                                                                </tbody>\r\n"
				+ "                                                                                            </table>\r\n"
				+ "                                                                                        </td>\r\n"
				+ "                                                                                    </tr>\r\n"
				+ "                                                                                </tbody>\r\n"
				+ "                                                                            </table> <img border=\"0\" height=\"1\" src=\"https://assets-global.website-files.com/62196607bf1b46c300301846/627120768c6e8b7f8e368a2a_hugo-illustration-calendar-extension.png\" style=\"display:none\"\r\n"
				+ "                                                                                width=\"1\" class=\"CToWUd\" data-bit=\"iit\" jslog=\"138226; u014N:xr6bB; 53:W2ZhbHNlLDJd\"></td>\r\n"
				+ "                                                                    </tr>\r\n"
				+ "                                                                </tbody>\r\n"
				+ "                                                            </table>\r\n"
				+ "                                                        </td>\r\n"
				+ "                                                    </tr>\r\n"
				+ "                                                </tbody>\r\n"
				+ "                                            </table>\r\n"
				+ "                                        </td>\r\n" + "                                    </tr>\r\n"
				+ "                                    <tr>\r\n" + "                                        <td>\r\n"
				+ "                                            <table style=\"width:100%\" role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
				+ "                                                <tbody>\r\n"
				+ "                                                    <tr>\r\n"
				+ "                                                        <td style=\"width:100%;padding-top:0px\" class=\"m_-3947633973872345608responsive-td\" valign=\"top\">\r\n"
				+ "                                                            <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" role=\"presentation\" style=\"min-width:100%\" class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                                                                <tbody>\r\n"
				+ "                                                                    <tr>\r\n"
				+ "                                                                        <td class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                                                                            <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\r\n"
				+ "                                                                                <tbody>\r\n"
				+ "                                                                                    <tr>\r\n"
				+ "                                                                                        <td style=\"line-height:64px;font-size:64px\" height=\"64\">\r\n"
				+ "                                                                                            &nbsp;</td>\r\n"
				+ "                                                                                    </tr>\r\n"
				+ "                                                                                </tbody>\r\n"
				+ "                                                                            </table>\r\n"
				+ "                                                                        </td>\r\n"
				+ "                                                                    </tr>\r\n"
				+ "                                                                </tbody>\r\n"
				+ "                                                            </table>\r\n"
				+ "                                                        </td>\r\n"
				+ "                                                    </tr>\r\n"
				+ "                                                </tbody>\r\n"
				+ "                                            </table>\r\n"
				+ "                                        </td>\r\n" + "                                    </tr>\r\n"
				+ "                                </tbody>\r\n" + "                            </table>\r\n"
				+ "                        </td>\r\n" + "                    </tr>\r\n" + "                </tbody>\r\n"
				+ "            </table>\r\n" + "        </td>\r\n" + "    </tr>\r\n" + "    </tbody>\r\n"
				+ "    </table>\r\n" + "    </td>";
		return body;
	}

	public String bodyTask(String fullname, String nameProject, String dealine, String taskName) {
		String body = " <td align=\"center\" valign=\"top\">\r\n"
				+ "        <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" width=\"600\" class=\"m_-3947633973872345608container\" style=\"margin:0 auto\">\r\n"
				+ "            <tbody>\r\n" + "                <tr>\r\n"
				+ "                    <td valign=\"top\" bgcolor=\"#FFFFFF\">\r\n"
				+ "                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" role=\"presentation\" style=\"min-width:100%\" class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                            <tbody>\r\n" + "                                <tr>\r\n"
				+ "                                    <td class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                                        <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" role=\"presentation\">\r\n"
				+ "                                            <tbody>\r\n"
				+ "                                                <tr>\r\n"
				+ "                                                    <td align=\"center\">\r\n"
				+ "                                                        <a href=\"#\" title=\"\" target=\"_blank\" data-saferedirecturl=\"https://assets-global.website-files.com/62196607bf1b46c300301846/627120768c6e8b7f8e368a2a_hugo-illustration-calendar-extension.png\"><img src=\"https://img.freepik.com/free-vector/business-man-dealing-multi-task-new-idea-working-laptop-concept-business-goals-success-satisfying-achievement_1150-39765.jpg?w=2000\" alt=\"\" width=\"1200\"\r\n"
				+ "                                                                style=\"display:block;padding:0px;text-align:center;height:auto;width:100%\" class=\"CToWUd\" data-bit=\"iit\"></a>\r\n"
				+ "                                                    </td>\r\n"
				+ "                                                </tr>\r\n"
				+ "                                            </tbody>\r\n"
				+ "                                        </table>\r\n"
				+ "                                    </td>\r\n" + "                                </tr>\r\n"
				+ "                            </tbody>\r\n" + "                        </table>\r\n"
				+ "                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" role=\"presentation\" style=\"background-color:transparent;min-width:100%\" class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                            <tbody>\r\n" + "                                <tr>\r\n"
				+ "                                    <td style=\"padding:40px 0px\" class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                                        <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
				+ "                                            <tbody>\r\n"
				+ "                                                <tr>\r\n"
				+ "                                                    <h2 style=\"color: #4d536e;text-align: center;\">The system PMF sends to you a message</h2>\r\n"
				+ "                                                </tr>\r\n"
				+ "                                                <h3 style=\"color: #4d536e;\">Hi, " + fullname
				+ "</h3>\r\n"
				+ "                                                <h3 style=\"color: #4d536e;\">From project: <b style=\"color: gray;\">"
				+ nameProject + "</b></h3>\r\n"
				+ "                                                <h3 style=\"color: #4d536e;\">Your task time is running out: : "
				+ dealine + "</h3>\r\n"
				+ "                                                <h3 style=\"color:#4d536e\">Task name: <b style=\"color: gray;\">"
				+ taskName + "</b></h3>\r\n"
				+ "                                                <p style=\"font-style: italic ;color:red;text-align: right;\">If you're done your task task, ignore this email</span>\r\n"
				+ "                                                    <p style=\"color:#4d536e;text-align: right;\">Have you a nice day!</p>\r\n"
				+ "                                            </tbody>\r\n"
				+ "                                        </table>\r\n"
				+ "                                    </td>\r\n" + "                                </tr>\r\n"
				+ "                            </tbody>\r\n" + "                        </table>\r\n"
				+ "                    </td>\r\n" + "                </tr>\r\n" + "            </tbody>\r\n"
				+ "        </table>\r\n" + "    </td>\r\n" + "    </tr>\r\n" + "    <tr>\r\n"
				+ "        <td valign=\"top\">\r\n"
				+ "            <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" role=\"presentation\" style=\"background-color:transparent;min-width:100%\" class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                <tbody>\r\n" + "                    <tr>\r\n"
				+ "                        <td style=\"padding:0px\" class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                            <table style=\"width:100%\" role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
				+ "                                <tbody>\r\n" + "                                    <tr>\r\n"
				+ "                                        <td>\r\n"
				+ "                                            <table style=\"width:100%\" role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
				+ "                                                <tbody>\r\n"
				+ "                                                    <tr>\r\n"
				+ "                                                        <td style=\"width:100%;padding-bottom:0px\" class=\"m_-3947633973872345608responsive-td\" valign=\"top\">\r\n"
				+ "                                                            <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" role=\"presentation\" style=\"min-width:100%\" class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                                                                <tbody>\r\n"
				+ "                                                                    <tr>\r\n"
				+ "                                                                        <td class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                                                                            <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
				+ "                                                                                <tbody>\r\n"
				+ "                                                                                    <tr>\r\n"
				+ "                                                                                        <td align=\"center\" valign=\"top\">\r\n"
				+ "                                                                                            <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"m_-3947633973872345608MobileTableWidth\" width=\"87%\">\r\n"
				+ "\r\n"
				+ "                                                                                                <tbody>\r\n"
				+ "\r\n"
				+ "                                                                                                    <tr>\r\n"
				+ "                                                                                                        <td style=\"font-weight:400;line-height:20px;font-size:14px;text-align:center;color:#4d536e\" valign=\"top\">\r\n"
				+ "                                                                                                            *This offer is active until 9/22/2022 and cannot be combined with other offers, discounts, or applied to prior purchases. <a href=\"https://click.send.grammarly.com/?qs=75b1430b8b349ea32b26c08b7fae0049c189564d9406f1a6cdc52fc58cd0a739d689f47fc2d36f99d6d557eb71c280df4ebdb6cff0252bb212f7d756f4ad0e46\"\r\n"
				+ "                                                                                                                style=\"text-decoration:none\" title=\"Additional terms\" target=\"_blank\" data-saferedirecturl=\"https://www.google.com/url?q=https://click.send.grammarly.com/?qs%3D75b1430b8b349ea32b26c08b7fae0049c189564d9406f1a6cdc52fc58cd0a739d689f47fc2d36f99d6d557eb71c280df4ebdb6cff0252bb212f7d756f4ad0e46&amp;source=gmail&amp;ust=1666882994849000&amp;usg=AOvVaw1Z8--l7NVr_Y0COmwDLiSv\">Additional terms</a>\r\n"
				+ "                                                                                                            <a href=\"https://click.send.grammarly.com/?qs=75b1430b8b349ea3728110c24108e8d108474e5f6bfa746b2163beb9fe00d2b880ade01e11fbf175a9a1cb094611636a6372d9a1729f434ad1ac8fce9509dbd0\" style=\"text-decoration:none\" title=\"Additional terms apply\" target=\"_blank\"\r\n"
				+ "                                                                                                                data-saferedirecturl=\"https://www.google.com/url?q=https://click.send.grammarly.com/?qs%3D75b1430b8b349ea3728110c24108e8d108474e5f6bfa746b2163beb9fe00d2b880ade01e11fbf175a9a1cb094611636a6372d9a1729f434ad1ac8fce9509dbd0&amp;source=gmail&amp;ust=1666882994849000&amp;usg=AOvVaw2aoeSg6c82LlbR5LUxgQBY\">\r\n"
				+ "                                                                                                            </a>apply.<br>\r\n"
				+ "                                                                                                            <br> You received this offer for Grammarly Premium because you are currently opted in to receive them via your preference settings. You may adjust\r\n"
				+ "                                                                                                            your preferences at any time by clicking the link above.<br>\r\n"
				+ "                                                                                                            <br> This offer is not valid for Grammarly Business purchases.<br>\r\n"
				+ "                                                                                                            <br> © 2022 Grammarly, Inc. 548 Market St. #35410, San Francisco, CA 94104</td>\r\n"
				+ "                                                                                                    </tr>\r\n"
				+ "                                                                                                </tbody>\r\n"
				+ "                                                                                            </table>\r\n"
				+ "                                                                                        </td>\r\n"
				+ "                                                                                    </tr>\r\n"
				+ "                                                                                </tbody>\r\n"
				+ "                                                                            </table> <img border=\"0\" height=\"1\" src=\"https://assets-global.website-files.com/62196607bf1b46c300301846/627120768c6e8b7f8e368a2a_hugo-illustration-calendar-extension.png\" style=\"display:none\"\r\n"
				+ "                                                                                width=\"1\" class=\"CToWUd\" data-bit=\"iit\" jslog=\"138226; u014N:xr6bB; 53:W2ZhbHNlLDJd\"></td>\r\n"
				+ "                                                                    </tr>\r\n"
				+ "                                                                </tbody>\r\n"
				+ "                                                            </table>\r\n"
				+ "                                                        </td>\r\n"
				+ "                                                    </tr>\r\n"
				+ "                                                </tbody>\r\n"
				+ "                                            </table>\r\n"
				+ "                                        </td>\r\n" + "                                    </tr>\r\n"
				+ "                                    <tr>\r\n" + "                                        <td>\r\n"
				+ "                                            <table style=\"width:100%\" role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
				+ "                                                <tbody>\r\n"
				+ "                                                    <tr>\r\n"
				+ "                                                        <td style=\"width:100%;padding-top:0px\" class=\"m_-3947633973872345608responsive-td\" valign=\"top\">\r\n"
				+ "                                                            <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" role=\"presentation\" style=\"min-width:100%\" class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                                                                <tbody>\r\n"
				+ "                                                                    <tr>\r\n"
				+ "                                                                        <td class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                                                                            <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\r\n"
				+ "                                                                                <tbody>\r\n"
				+ "                                                                                    <tr>\r\n"
				+ "                                                                                        <td style=\"line-height:64px;font-size:64px\" height=\"64\">\r\n"
				+ "                                                                                            &nbsp;</td>\r\n"
				+ "                                                                                    </tr>\r\n"
				+ "                                                                                </tbody>\r\n"
				+ "                                                                            </table>\r\n"
				+ "                                                                        </td>\r\n"
				+ "                                                                    </tr>\r\n"
				+ "                                                                </tbody>\r\n"
				+ "                                                            </table>\r\n"
				+ "                                                        </td>\r\n"
				+ "                                                    </tr>\r\n"
				+ "                                                </tbody>\r\n"
				+ "                                            </table>\r\n"
				+ "                                        </td>\r\n" + "                                    </tr>\r\n"
				+ "                                </tbody>\r\n" + "                            </table>\r\n"
				+ "                        </td>\r\n" + "                    </tr>\r\n" + "                </tbody>\r\n"
				+ "            </table>\r\n" + "        </td>\r\n" + "    </tr>\r\n" + "    </tbody>\r\n"
				+ "    </table>\r\n" + "    </td>";
		return body;
	}

	public String bodyCodeVerify(String email, int codeVerify) {
		String body = "<table style=\"background-color:#eaeaea;background-image:url(https://ci4.googleusercontent.com/proxy/1LXf5RqjzCAAG_7qLOmmp0GJoi8g6OcQhbVyrWuNf7cbyhtfEkGMamPfj4_iewJVRzZtlwHyEu5YiBKq1QM4xoahZ9UVhGr2bMPdwekDwA=s0-d-e1-ft#https://www.twilio.com/resources/images/email/background.jpg);border:0;border-collapse:collapse;border-spacing:0;box-sizing:inherit;font:inherit;font-family:Whitney-SSm-A,Whitney-SSm-B,Whitney,Helvetica Neue,Helvetica,Arial,sans-serif;font-size:100%;font-weight:300;height:100vh;line-height:100%;margin:0;padding:0;text-align:center;vertical-align:baseline;width:100%\">\r\n"
				+ "    <tbody style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;margin:0;padding:0;vertical-align:baseline\">\r\n"
				+ "        <tr style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;margin:0;padding:0;vertical-align:baseline\">\r\n"
				+ "            <td style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;height:20px;margin:0;padding:0;vertical-align:middle\"></td>\r\n"
				+ "        </tr>\r\n"
				+ "        <tr style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;margin:0;padding:0;vertical-align:baseline\">\r\n"
				+ "            <td style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;margin:0;padding:0;vertical-align:top\">\r\n"
				+ "                <table style=\"background-color:#fff;border:0;border-collapse:collapse;border-color:#ddd;border-spacing:0;border-style:solid;border-width:1px;box-sizing:inherit;font:inherit;font-size:100%;margin:0 auto;max-width:680px;padding:0;vertical-align:baseline;width:100%\">\r\n"
				+ "                    <tbody style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;margin:0;padding:0;vertical-align:baseline\">\r\n"
				+ "                        <tr style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;margin:0;padding:0;vertical-align:baseline\">\r\n"
				+ "                            <td style=\"border:0;border-bottom-color:#ddd;border-bottom-style:solid;border-bottom-width:1px;box-sizing:inherit;font:inherit;font-size:100%;margin:0;padding-left:20px;vertical-align:middle;height:70px\" align=\"left\"><img height=\"35\" style=\"border:0;border-style:none;box-sizing:inherit;font:inherit;font-size:100%;margin:0;outline:none;padding:0;text-decoration:none;vertical-align:baseline\" src=\"https://f5-zpc.zdn.vn/3011992379074828791/a9c860db8d7854260d69.jpg\"\r\n"
				+ "                                    alt=\"Twilio\" class=\"CToWUd\" data-bit=\"iit\"></td>\r\n"
				+ "                        </tr>\r\n"
				+ "                        <tr style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;margin:0;padding:0;vertical-align:baseline;text-align:left\">\r\n"
				+ "                            <td style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;height:70px;margin:0;padding:0;vertical-align:middle\">\r\n"
				+ "                                <p style=\"border:0;box-sizing:inherit;color:rgb(57,62,64);font:inherit;font-size:24px;line-height:32px;margin-left:50px;margin-right:50px;max-width:558px;padding:0;vertical-align:baseline\"> "+email+", </p>\r\n"
				+ "                            </td>\r\n" + "                        </tr>\r\n"
				+ "                        <tr style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;margin:0;padding:0;vertical-align:baseline;text-align:left\">\r\n"
				+ "                            <td style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;height:20px;margin:0;padding:0;vertical-align:middle\">\r\n"
				+ "                                <p style=\"border:0;box-sizing:inherit;color:rgb(34,34,34);font:inherit;font-size:14px;font-weight:300;line-height:20px;margin-left:50px;margin-right:50px;padding:0;vertical-align:baseline\">We have sent you a code to verify your account, use the code below to verify your account.</p>\r\n"
				+ "                            </td>\r\n" + "                        </tr>\r\n"
				+ "                        <tr style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;margin:0;padding:0;vertical-align:baseline;text-align:left\">\r\n"
				+ "                            <td style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;height:20px;margin:0;padding:0;vertical-align:middle\">\r\n"
				+ "                                <p style=\"border:0;box-sizing:inherit;color:rgb(34,34,34);font:inherit;font-size:14px;font-weight:300;line-height:20px;margin-left:50px;margin-right:50px;padding:0;vertical-align:baseline\">Your code verify is: <b style=\"font-weight: bold;\">"+codeVerify+"</b> </p>\r\n"
				+ "                            </td>\r\n" + "                        </tr>\r\n"
				+ "                        <tr style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;margin:0;padding:0;vertical-align:baseline;text-align:left\">\r\n"
				+ "                            <td style=\"border:0;box-sizing:inherit;font:inherit;font-size:100%;height:90px;margin:0;padding:0;vertical-align:middle\">\r\n"
				+ "                                <p style=\"border:0;box-sizing:inherit;color:rgb(34,34,34);font:inherit;font-size:14px;font-weight:300;line-height:20px;margin-left:50px;margin-right:50px;padding:0;vertical-align:baseline\"> - Team PMF </p>\r\n"
				+ "                            </td>\r\n" + "                        </tr>\r\n"
				+ "                    </tbody>\r\n" + "                </table>\r\n"
				+ "                <p style=\"border:0;box-sizing:inherit;color:rgb(34,34,34);font:inherit;font-size:12px;font-weight:normal;margin-top:20px;padding:0;vertical-align:baseline\">PMF, 375 Beale St, San Francisco, CA 94105</p>\r\n"
				+ "            </td>\r\n" + "        </tr>\r\n" + "    </tbody>\r\n" + "</table>";
		return body;
	}
	public String sendMaillAlertMeeting(String fullname,String fromProject,String creator,String timeBegin) {
		String body="\r\n"
				+ "    <td align=\"center\" valign=\"top\">\r\n"
				+ "        <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" width=\"600\" class=\"m_-3947633973872345608container\" style=\"margin:0 auto\">\r\n"
				+ "            <tbody>\r\n"
				+ "                <tr>\r\n"
				+ "                    <td valign=\"top\" bgcolor=\"#FFFFFF\">\r\n"
				+ "                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" role=\"presentation\" style=\"min-width:100%\" class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                            <tbody>\r\n"
				+ "                                <tr>\r\n"
				+ "                                    <td class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                                        <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" role=\"presentation\">\r\n"
				+ "                                            <tbody>\r\n"
				+ "                                                <tr>\r\n"
				+ "                                                    <td align=\"center\">\r\n"
				+ "                                                        <a href=\"#\" title=\"\" target=\"_blank\" data-saferedirecturl=\"https://assets-global.website-files.com/62196607bf1b46c300301846/627120768c6e8b7f8e368a2a_hugo-illustration-calendar-extension.png\"><img src=\"https://f29-zpc.zdn.vn/9050641854170758069/976f60cab1ee69b030ff.jpg\" alt=\"\" width=\"1200\" style=\"display:block;padding:0px;text-align:center;height:auto;width:100%\" class=\"CToWUd\" data-bit=\"iit\"></a>\r\n"
				+ "                                                    </td>\r\n"
				+ "                                                </tr>\r\n"
				+ "                                            </tbody>\r\n"
				+ "                                        </table>\r\n"
				+ "                                    </td>\r\n"
				+ "                                </tr>\r\n"
				+ "                            </tbody>\r\n"
				+ "                        </table>\r\n"
				+ "                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" role=\"presentation\" style=\"background-color:transparent;min-width:100%\" class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                            <tbody>\r\n"
				+ "                                <tr>\r\n"
				+ "                                    <td style=\"padding:40px 0px\" class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                                        <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
				+ "                                            <tbody>\r\n"
				+ "                                                <tr>\r\n"
				+ "                                                    <h2 style=\"color: #4d536e;text-align: center;\">The system PMF sends to you a message</h2>\r\n"
				+ "                                                </tr>\r\n"
				+ "                                                <h3 style=\"color: #4d536e;\">Hi, "+fullname+"</h3>\r\n"
				+ "                                                <h3 style=\"color: #4d536e;\">From project: <b style=\"color: gray;\">"+fromProject+"</b></h3>\r\n"
				+ "                                                <h3 style=\"color: #4d536e;\">You have a meeting created by : "+creator+"</h3>\r\n"
				+ "                                                <h3 style=\"color:#4d536e\">The meeting begins on: <b style=\"color: red;\">"+timeBegin+"</b></h3>\r\n"
				+ "                                                <p style=\"color:#4d536e; margin-top: 10px;\">Please confirm to join the meeting at our app!</p>\r\n"
				+ "                                                <div style=\"display: flex;justify-content: center;align-items: center;\">\r\n"
				+ "                                                    <button style=\"\r\n"
				+ "                                                    background-color: #e83030;\r\n"
				+ "                                                    color: white;\r\n"
				+ "                                                    font-weight: bold;\r\n"
				+ "                                                    padding: 5px;\r\n"
				+ "                                                    padding-left: 17px;\r\n"
				+ "                                                    padding-right: 17px;\r\n"
				+ "                                                    border-radius: 3px;\r\n"
				+ "                                                    border: none;\r\n"
				+ "                                                    width: 35%;\r\n"
				+ "                                                    height: 50px;\r\n"
				+ "                                                    min-width: 50px;\r\n"
				+ "                                                    box-shadow: 0 5px 0 rgb(185, 185, 185);\r\n"
				+ "                                                    margin: 2px;cursor: pointer;\" onclick=\"window.location.href='http://127.0.0.1:5502/template/client/meeting/create-meeting.html'\">Confirm the meeting</button>\r\n"
				+ "                                                </div>\r\n"
				+ "\r\n"
				+ "                                                <p style=\"color:#4d536e;text-align: center;\">Have you a nice day!</p>\r\n"
				+ "                                            </tbody>\r\n"
				+ "                                        </table>\r\n"
				+ "                                    </td>\r\n"
				+ "                                </tr>\r\n"
				+ "                            </tbody>\r\n"
				+ "                        </table>\r\n"
				+ "                    </td>\r\n"
				+ "                </tr>\r\n"
				+ "            </tbody>\r\n"
				+ "        </table>\r\n"
				+ "    </td>\r\n"
				+ "    </tr>\r\n"
				+ "    <tr>\r\n"
				+ "        <td valign=\"top\">\r\n"
				+ "            <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" role=\"presentation\" style=\"background-color:transparent;min-width:100%\" class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                <tbody>\r\n"
				+ "                    <tr>\r\n"
				+ "                        <td style=\"padding:0px\" class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                            <table style=\"width:100%\" role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
				+ "                                <tbody>\r\n"
				+ "                                    <tr>\r\n"
				+ "                                        <td>\r\n"
				+ "                                            <table style=\"width:100%\" role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
				+ "                                                <tbody>\r\n"
				+ "                                                    <tr>\r\n"
				+ "                                                        <td style=\"width:100%;padding-bottom:0px\" class=\"m_-3947633973872345608responsive-td\" valign=\"top\">\r\n"
				+ "                                                            <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" role=\"presentation\" style=\"min-width:100%\" class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                                                                <tbody>\r\n"
				+ "                                                                    <tr>\r\n"
				+ "                                                                        <td class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                                                                            <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
				+ "                                                                                <tbody>\r\n"
				+ "                                                                                    <tr>\r\n"
				+ "                                                                                        <td align=\"center\" valign=\"top\">\r\n"
				+ "                                                                                            <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"m_-3947633973872345608MobileTableWidth\" width=\"87%\">\r\n"
				+ "\r\n"
				+ "                                                                                                <tbody>\r\n"
				+ "\r\n"
				+ "                                                                                                    <tr>\r\n"
				+ "                                                                                                        <td style=\"font-weight:400;line-height:20px;font-size:14px;text-align:center;color:#4d536e\" valign=\"top\">\r\n"
				+ "                                                                                                            *This offer is active until 9/22/2022 and cannot be combined with other offers, discounts, or applied to prior purchases. <a href=\"https://click.send.grammarly.com/?qs=75b1430b8b349ea32b26c08b7fae0049c189564d9406f1a6cdc52fc58cd0a739d689f47fc2d36f99d6d557eb71c280df4ebdb6cff0252bb212f7d756f4ad0e46\"\r\n"
				+ "                                                                                                                style=\"text-decoration:none\" title=\"Additional terms\" target=\"_blank\" data-saferedirecturl=\"https://www.google.com/url?q=https://click.send.grammarly.com/?qs%3D75b1430b8b349ea32b26c08b7fae0049c189564d9406f1a6cdc52fc58cd0a739d689f47fc2d36f99d6d557eb71c280df4ebdb6cff0252bb212f7d756f4ad0e46&amp;source=gmail&amp;ust=1666882994849000&amp;usg=AOvVaw1Z8--l7NVr_Y0COmwDLiSv\">Additional terms</a>\r\n"
				+ "                                                                                                            <a href=\"https://click.send.grammarly.com/?qs=75b1430b8b349ea3728110c24108e8d108474e5f6bfa746b2163beb9fe00d2b880ade01e11fbf175a9a1cb094611636a6372d9a1729f434ad1ac8fce9509dbd0\" style=\"text-decoration:none\" title=\"Additional terms apply\" target=\"_blank\"\r\n"
				+ "                                                                                                                data-saferedirecturl=\"https://www.google.com/url?q=https://click.send.grammarly.com/?qs%3D75b1430b8b349ea3728110c24108e8d108474e5f6bfa746b2163beb9fe00d2b880ade01e11fbf175a9a1cb094611636a6372d9a1729f434ad1ac8fce9509dbd0&amp;source=gmail&amp;ust=1666882994849000&amp;usg=AOvVaw2aoeSg6c82LlbR5LUxgQBY\">\r\n"
				+ "                                                                                                            </a>apply.<br>\r\n"
				+ "                                                                                                            <br> You received this offer for Grammarly Premium because you are currently opted in to receive them via your preference settings. You may adjust\r\n"
				+ "                                                                                                            your preferences at any time by clicking the link above.<br>\r\n"
				+ "                                                                                                            <br> This offer is not valid for Grammarly Business purchases.<br>\r\n"
				+ "                                                                                                            <br> © 2022 Grammarly, Inc. 548 Market St. #35410, San Francisco, CA 94104</td>\r\n"
				+ "                                                                                                    </tr>\r\n"
				+ "                                                                                                </tbody>\r\n"
				+ "                                                                                            </table>\r\n"
				+ "                                                                                        </td>\r\n"
				+ "                                                                                    </tr>\r\n"
				+ "                                                                                </tbody>\r\n"
				+ "                                                                            </table> <img border=\"0\" height=\"1\" src=\"https://assets-global.website-files.com/62196607bf1b46c300301846/627120768c6e8b7f8e368a2a_hugo-illustration-calendar-extension.png\" style=\"display:none\"\r\n"
				+ "                                                                                width=\"1\" class=\"CToWUd\" data-bit=\"iit\" jslog=\"138226; u014N:xr6bB; 53:W2ZhbHNlLDJd\"></td>\r\n"
				+ "                                                                    </tr>\r\n"
				+ "                                                                </tbody>\r\n"
				+ "                                                            </table>\r\n"
				+ "                                                        </td>\r\n"
				+ "                                                    </tr>\r\n"
				+ "                                                </tbody>\r\n"
				+ "                                            </table>\r\n"
				+ "                                        </td>\r\n"
				+ "                                    </tr>\r\n"
				+ "                                    <tr>\r\n"
				+ "                                        <td>\r\n"
				+ "                                            <table style=\"width:100%\" role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
				+ "                                                <tbody>\r\n"
				+ "                                                    <tr>\r\n"
				+ "                                                        <td style=\"width:100%;padding-top:0px\" class=\"m_-3947633973872345608responsive-td\" valign=\"top\">\r\n"
				+ "                                                            <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" role=\"presentation\" style=\"min-width:100%\" class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                                                                <tbody>\r\n"
				+ "                                                                    <tr>\r\n"
				+ "                                                                        <td class=\"m_-3947633973872345608stylingblock-content-wrapper\">\r\n"
				+ "                                                                            <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\r\n"
				+ "                                                                                <tbody>\r\n"
				+ "                                                                                    <tr>\r\n"
				+ "                                                                                        <td style=\"line-height:64px;font-size:64px\" height=\"64\">\r\n"
				+ "                                                                                            &nbsp;</td>\r\n"
				+ "                                                                                    </tr>\r\n"
				+ "                                                                                </tbody>\r\n"
				+ "                                                                            </table>\r\n"
				+ "                                                                        </td>\r\n"
				+ "                                                                    </tr>\r\n"
				+ "                                                                </tbody>\r\n"
				+ "                                                            </table>\r\n"
				+ "                                                        </td>\r\n"
				+ "                                                    </tr>\r\n"
				+ "                                                </tbody>\r\n"
				+ "                                            </table>\r\n"
				+ "                                        </td>\r\n"
				+ "                                    </tr>\r\n"
				+ "                                </tbody>\r\n"
				+ "                            </table>\r\n"
				+ "                        </td>\r\n"
				+ "                    </tr>\r\n"
				+ "                </tbody>\r\n"
				+ "            </table>\r\n"
				+ "        </td>\r\n"
				+ "    </tr>\r\n"
				+ "    </tbody>\r\n"
				+ "    </table>\r\n"
				+ "    </td>";
		return body;
	}
}
